// French translation helpers for the awesome-mcp-servers README.
// Token-safe: this module only ever translates natural-language prose.
// Placeholder tokens (@@Lx@@ / @@Cx@@) are handled by the pipeline, never here.

// Words/phrases kept verbatim (acronyms + proper nouns).
export const SKIP = new Set([
  "mcp", "api", "apis", "json", "url", "urls", "sdk", "sdks", "cli", "llm", "llms",
  "ai", "oauth", "http", "https", "ide", "sql", "xml", "csv", "pdf", "png", "jpg",
  "jpeg", "svg", "gif", "html", "css", "uri", "rgb", "yaml", "toml", "md", "ui",
  "ux", "iot", "jwt", "tls", "ssl", "dns", "who", "ip", "mac", "os", "db", "id",
  "ids", "qr", "iso", "utc", "gps", "nlp", "ocr", "tts", "stt", "cd", "dvd",
  "usdc", "usdt", "evm", "rpc", "rest", "graphql", "soap", "fhir", "hl7", "dicom",
  "tcp", "udp", "ssh", "ftp", "smtp", "imap", "pop", "wifi", "lan", "vpn", "cms",
  "x402", "l402", "base", "solana", "algorand", "bitcoin", "ethereum", "polygon",
  "arbitrum", "optimism", "starknet", "tron", "stellar", "lightning", "cashu",
  "github", "gitlab", "notion", "slack", "discord", "reddit", "telegram", "whatsapp",
  "figma", "blender", "spotify", "youtube", "bilibili", "steam", "openai", "gemini",
  "claude", "gpt", "grok", "deepseek", "qwen", "mistral", "llama", "ollama",
  "anthropic", "google", "apple", "microsoft", "azure", "aws", "gcp", "datadog",
  "postgresql", "postgres", "mysql", "sqlite", "mongodb", "redis", "kafka",
  "docker", "kubernetes", "terraform", "fastapi", "spring", "playwright", "selenium",
  "chrome", "firefox", "safari", "chromium", "arc", "vivaldi", "brave", "cursor",
  "photopea", "manim", "comfyui", "reaper", "ableton", "flstudio", "maya",
  "autodesk", "revit", "freecad", "fusion", "brics", "wordpress", "shopify", "stripe",
  "twilio", "sendgrid", "resend", "supabase", "vercel", "neon", "upstash",
  "cloudflare", "hugging", "fal", "runcomfy", "pixelfed", "mastodon", "bluesky",
  "nostr", "sol", "usd", "eur", "gbp", "jpy", "glama", "davinci", "resolve",
  "bazi", "persian", "gregorian", "rfc", "eip", "nip", "jpl", "nasada", "dmtf",
  "bmc", "idrac", "ilo", "xcc", "openbmc", "openngc", "ismlp", "lrc", "lrclib",
  "opds", "ro", "crate", "nextflow", "mermaid", "graphviz", "excalidraw", "draw",
  "kroki", "sysml", "uml", "erd", "ascii", "dsl", "cad", "fem", "cfd", "em",
  "gromacs", "lammps", "pymol", "babel", "pdb", "smiles", "sdf", "openbabel",
  "gds", "oasis", "opc", "plc", "scada", "modbus", "bacnet", "knx", "zigbee",
  "matter", "homekit", "mqtt", "z-wave", "thread", "lora", "ble", "usb", "hdmi",
  "gpio", "spi", "i2c", "uart", "can", "rs232", "rs485", "epub", "docx", "xlsx",
  "pptx", "odt", "rtf", "tex", "bib", "ris", "csl", "zotero", "mendeley",
  "endnote", "calibre", "kindle", "audible", "twitch", "tiktok", "instagram",
  "facebook", "linkedin", "medium", "substack", "patreon", "kickstarter",
  "gofundme", "paypal", "venmo", "cashapp", "coinbase", "binance", "kraken",
  "bybit", "okx", "uniswap", "aave", "compound", "maker", "lido", "rocketpool",
  "chainlink", "thegraph", "immutable", "opensea", "blur", "rarible", "foundation",
  "superrare", "knownorigin", "nft", "defi", "dao", "dex", "cex", "amm", "lp",
  "tvl", "apy", "apr", "bps", "tps", "mcap", "fdv", "blockchain", "onchain",
  "multichain", "cross", "wallet", "seed", "phrase", "private", "pubkey", "tx",
  "merkle", "zk", "rollup", "l2", "l1", "sidechain", "parachain", "consensus",
  "pos", "pow", "dpos", "pbft", "tendermint", "cosmos", "polkadot", "substrate",
  "wormhole", "layerzero", "axelar", "celer", "connext", "hop", "stargate",
  "synapse", "jupiter", "raydium", "orca", "serum", "meteora", "pump", "bonk",
  "jto", "pyth", "switchboard", "openusd", "isaac", "nvidia", "imagen", "veo",
  "sora", "kling", "elevenlabs", "flux", "nanobanana", "nano", "bananas",
  "tmdb", "imdb", "discogs", "anilist", "met", "ao3", "l402", "fcc", "itu",
  "unoosa", "faa", "nih", "nhi", "cid", "datasus", "ehr", "dexcom", "libre",
  "oura", "fitbit", "pixel", "openmcp", "openlibrary", "pmc", "doi", "pmid",
  "fda", "nhtsa", "icd", "cpt", "hcpcs", "loinc", "rxnorm", "mesh", "atc",
  "snomed", "omop", "hipaa", "euipo", "ncbi", "blast", "pubmed", "arxiv",
  "kds", "kcs", "ks", "uniprot", "ensembl", "phytozome", "kegg", "string",
  "french", "france", "chinese", "japanese", "korean", "english", "russian",
  "arabic", "hebrew", "taiwan", "netherlands", "california", "hawaii", "korea",
  "spain", "italy", "germany", "europe", "european", "us", "uk", "eu",
  "wikipedia", "wikimedia", "metmuseum", "rijksmuseum", "smithsonian", "met",
  "openaccess", "oorlogsbronnen", "bibliotheque", "nationale", "loc", "ia",
  "gpt", "chatgpt", "perplexity", "codex", "gpt", "openai", "gpt", "sdxl",
  "bun", "deno", "node", "npm", "pip", "conda", "venv", "pyenv", "nvm",
  "typescript", "javascript", "python", "rust", "golang", "java", "csharp",
  "cpp", "c", "ruby", "php", "kotlin", "swift", "scala", "dart", "elixir",
  "haskell", "lua", "r", "matlab", "julia", "cobol", "fortran", "assembly",
  "bash", "powershell", "sh", "zsh", "fish", "awk", "sed", "grep", "vim",
  "emacs", "vscode", "intellij", "eclipse", "xcode", "android", "ios",
  "macos", "windows", "linux", "ubuntu", "debian", "fedora", "arch", "centos",
  "redhat", "alpine", "raspbian", "chromeos", "webos", "tvos", "watchos",
]);

// Multi-word phrases (applied first, case-insensitive).
export const PHRASES = [
  [/\bself[- ]hosted\b/gi, "auto-hébergé"],
  [/\blocal[- ]first\b/gi, "local-first"],
  [/\bcloud[- ]native\b/gi, "cloud-native"],
  [/\bcloud service\b/gi, "service cloud"],
  [/\blocal service\b/gi, "service local"],
  [/\bremote resources?\b/gi, "ressources distantes"],
  [/\blocal and remote\b/gi, "locales et distantes"],
  [/\bproduction[- ]grade\b/gi, "de qualité production"],
  [/\bproduction-ready\b/gi, "prêt pour la production"],
  [/\bopen (?:protocol|standard)\b/gi, "protocole ouvert"],
  [/\bopen source\b/gi, "open source"],
  [/\bopen-source\b/gi, "open source"],
  [/\bmodel context protocol\b/gi, "Model Context Protocol"],
  [/\bnatural language\b/gi, "langage naturel"],
  [/\blarge language model\b/gi, "grand modèle de langage"],
  [/\bmachine learning\b/gi, "apprentissage automatique"],
  [/\bdeep learning\b/gi, "apprentissage profond"],
  [/\breal[- ]?time\b/gi, "temps réel"],
  [/\bout of the box\b/gi, "prêt à l'emploi"],
  [/\bstate of the art\b/gi, "l'état de l'art"],
  [/\bcutting[- ]edge\b/gi, "de pointe"],
  [/\bend[- ]to[- ]end\b/gi, "de bout en bout"],
  [/\bpoint and click\b/gi, "pointer-et-cliquer"],
  [/\bdrag and drop\b/gi, "glisser-déposer"],
  [/\bsearch and retrieve\b/gi, "rechercher et récupérer"],
  [/\bsearch and browse\b/gi, "rechercher et parcourir"],
  [/\bcreate,? read,? update,? (?:and )?delete\b/gi, "créer, lire, mettre à jour et supprimer"],
  [/\bread[- ]only\b/gi, "en lecture seule"],
  [/\bwrite[- ]only\b/gi, "en écriture seule"],
  [/\bzero configuration\b/gi, "sans configuration"],
  [/\bzero-config\b/gi, "sans configuration"],
  [/\bno[- ]code\b/gi, "sans code"],
  [/\blow[- ]code\b/gi, "low-code"],
  [/\bagent[- ]to[- ]agent\b/gi, "agent-à-agent"],
  [/\bhuman[- ]in[- ]the[- ]loop\b/gi, "human-in-the-loop"],
  [/\bpay[- ]per[- ]call\b/gi, "paiement à la demande"],
  [/\bpay per use\b/gi, "paiement à l'usage"],
  [/\bper[- ]call\b/gi, "par appel"],
  [/\bper[- ]use\b/gi, "par utilisation"],
  [/\bon demand\b/gi, "à la demande"],
  [/\bout of band\b/gi, "hors bande"],
  [/\bturn[- ]key\b/gi, "clé en main"],
  [/\bbest[- ]in[- ]class\b/gi, "de classe mondiale"],
  [/\bthird[- ]party\b/gi, "tiers"],
  [/\bfirst[- ]party\b/gi, "de première partie"],
  [/\bsingle[- ]sign[- ]on\b/gi, "authentification unique"],
  [/\bsign[- ]in\b/gi, "connexion"],
  [/\bsign[- ]up\b/gi, "inscription"],
  [/\blog[- ]in\b/gi, "se connecter"],
  [/\bstep[- ]by[- ]step\b/gi, "étape par étape"],
  [/\bone[- ]click\b/gi, "en un clic"],
  [/\bone click\b/gi, "en un clic"],
  [/\bin[- ]memory\b/gi, "en mémoire"],
  [/\bserver[- ]side\b/gi, "côté serveur"],
  [/\bclient[- ]side\b/gi, "côté client"],
  [/\bfront[- ]end\b/gi, "front-end"],
  [/\bback[- ]end\b/gi, "back-end"],
  [/\bfull[- ]stack\b/gi, "full-stack"],
  [/\bcost[- ]effective\b/gi, "rentable"],
  [/\bhigh[- ]performance\b/gi, "haute performance"],
  [/\blow[- ]latency\b/gi, "faible latence"],
  [/\bwell[- ]architected\b/gi, "bien architecturé"],
  [/\bself[- ]service\b/gi, "en libre-service"],
  [/\bup[- ]to[- ]date\b/gi, "à jour"],
  [/\bout[- ]of[- ]date\b/gi, "obsolète"],
  [/\btime[- ]zone\b/gi, "fuseau horaire"],
  [/\bbusiness days?\b/gi, "jours ouvrables"],
  [/\bpublic holidays?\b/gi, "jours fériés"],
  [/\bmachine[- ]readable\b/gi, "lisible par machine"],
  [/\bhuman[- ]readable\b/gi, "lisible par l'homme"],
  [/\bdeveloper[- ]friendly\b/gi, "convivial pour les développeurs"],
  [/\bagent[- ]friendly\b/gi, "convivial pour les agents"],
  [/\buser[- ]friendly\b/gi, "convivial"],
  [/\brule[- ]based\b/gi, "basé sur des règles"],
  [/\bpolicy[- ]based\b/gi, "basé sur des politiques"],
  [/\btoken[- ]based\b/gi, "basé sur les jetons"],
  [/\bevent[- ]driven\b/gi, "orienté événements"],
  [/\bdata[- ]driven\b/gi, "orienté données"],
  [/\bai[- ]powered\b/gi, "alimenté par l'IA"],
  [/\bcloud[- ]based\b/gi, "basé sur le cloud"],
  [/\bweb[- ]based\b/gi, "basé sur le web"],
  [/\bapi[- ]first\b/gi, "API-first"],
  [/\bgit[- ]based\b/gi, "basé sur Git"],
  [/\bfile[- ]based\b/gi, "basé sur des fichiers"],
  [/\bbrowser[- ]based\b/gi, "basé sur le navigateur"],
  [/\bcontainer[- ]based\b/gi, "basé sur des conteneurs"],
  [/\bmicro[- ]service\b/gi, "microservice"],
  [/\bserverless\b/gi, "sans serveur"],
  [/\bheadless\b/gi, "headless"],
  [/\bself[- ]improving\b/gi, "auto-améliorant"],
  [/\bself[- ]documenting\b/gi, "auto-documenté"],
  [/\bself[- ]hosting\b/gi, "auto-hébergement"],
  [/\bself[- ]signed\b/gi, "auto-signé"],
  [/\bself[- ]contained\b/gi, "autonome"],
  [/\bx402-payable\b/gi, "payable en x402"],
  [/\bx402 payment\b/gi, "paiement x402"],
  [/\bx402-enabled\b/gi, "compatible x402"],
  [/\bx402 discovery\b/gi, "découverte x402"],
  [/\bfederal register\b/gi, "registre fédéral"],
  [/\bscientific papers?\b/gi, "articles scientifiques"],
  [/\bcase law\b/gi, "jurisprudence"],
  [/\bprediction markets?\b/gi, "marchés prédictifs"],
  [/\bthe bible\b/gi, "la Bible"],
  [/\bthe met\b/gi, "le Met"],
  [/\bFHIR servers?\b/gi, "serveurs FHIR"],
  [/\bSMART-on-FHIR\b/gi, "SMART-on-FHIR"],
  [/\bfor example\b/gi, "par exemple"],
  [/\bsuch as\b/gi, "tels que"],
  [/\bbased on\b/gi, "basé sur"],
  [/\bwith support for\b/gi, "avec prise en charge de"],
  [/\bout of the box\b/gi, "prêt à l'emploi"],
];

// Compact word map (lower-case key -> French). Not exhaustive; unknown words pass through.
export const WORDS = {
  // verbs
  access: "accéder à", accessed: "accédé", accesses: "accède à", accessing: "accès à",
  connect: "connecter", connects: "connecte", connected: "connecté", connecting: "connexion",
  search: "rechercher", searches: "recherche", searched: "recherché", searching: "recherche",
  browse: "parcourir", browses: "parcourt", browsed: "parcouru", browsing: "parcours",
  retrieve: "récupérer", retrieves: "récupère", retrieved: "récupéré", retrieving: "récupération",
  create: "créer", creates: "crée", created: "créé", creating: "création",
  read: "lire", reads: "lit", reading: "lecture",
  write: "écrire", writes: "écrit", writing: "écriture",
  manage: "gérer", manages: "gère", managed: "géré", managing: "gestion", management: "gestion",
  generate: "générer", generates: "génère", generated: "généré", generating: "génération", generation: "génération",
  control: "contrôler", controls: "contrôle", controlled: "contrôlé", controlling: "contrôle",
  query: "interroger", queries: "interroge", queried: "interrogé", querying: "interrogation",
  interact: "interagir", interacts: "interagit", interacting: "interaction", interaction: "interaction",
  view: "afficher", views: "affiche", viewed: "affiché", viewing: "visualisation",
  edit: "modifier", edits: "modifie", edited: "modifié", editing: "édition",
  run: "exécuter", runs: "exécute", ran: "exécuté", running: "exécution",
  execute: "exécuter", executes: "exécute", executed: "exécuté", execution: "exécution",
  build: "construire", builds: "construit", built: "construit", building: "construction",
  deploy: "déployer", deploys: "déploie", deployed: "déployé", deploying: "déploiement", deployment: "déploiement",
  turn: "transformer", turning: "transformation",
  bridge: "relie", bridges: "relie", bridged: "relié", bridging: "mise en relation",
  send: "envoyer", sends: "envoie", sent: "envoyé", sending: "envoi",
  get: "obtenir", gets: "obtient", got: "obtenu", getting: "obtention",
  find: "trouver", finds: "trouve", found: "trouvé", finding: "recherche",
  discover: "découvrir", discovers: "découvre", discovered: "découvert", discovering: "découverte", discovery: "découverte",
  install: "installer", installs: "installe", installed: "installé", installing: "installation", installation: "installation",
  use: "utiliser", uses: "utilise", used: "utilisé", using: "utilisation",
  analyze: "analyser", analyzes: "analyse", analysed: "analysé", analyzing: "analyse", analyse: "analyser", analysis: "analyse",
  monitor: "surveiller", monitors: "surveille", monitored: "surveillé", monitoring: "surveillance",
  track: "suivre", tracks: "suit", tracked: "suivi", tracking: "suivi",
  convert: "convertir", converts: "convertit", converted: "converti", converting: "conversion", conversion: "conversion",
  export: "exporter", exports: "exporte", exported: "exporté", exporting: "exportation",
  import: "importer", imports: "importe", imported: "importé", importing: "importation",
  render: "rendre", renders: "rend", rendered: "rendu", rendering: "rendu",
  list: "lister", lists: "liste", listed: "répertorié", listing: "liste",
  organize: "organiser", organizes: "organise", organized: "organisé", organising: "organisation", organising: "organisation",
  automate: "automatiser", automates: "automatise", automated: "automatisé", automating: "automatisation", automation: "automatisation",
  scrape: "extraire", scrapes: "extrait", scraped: "extrait", scraping: "extraction",
  crawl: "explorer", crawls: "explore", crawled: "exploré", crawling: "exploration",
  map: "cartographier", maps: "cartographie", mapped: "cartographié", mapping: "cartographie",
  provide: "fournir", provides: "fournit", provided: "fourni", providing: "fourniture",
  support: "prendre en charge", supports: "prend en charge", supported: "pris en charge", supporting: "prise en charge",
  enable: "permettre", enables: "permet", enabled: "activé", enabling: "activation",
  extend: "étendre", extends: "étend", extended: "étendu", extending: "extension", extension: "extension",
  integrate: "intégrer", integrates: "intègre", integrated: "intégré", integrating: "intégration", integration: "intégration",
  fetch: "récupérer", fetches: "récupère", fetched: "récupéré", fetching: "récupération",
  load: "charger", loads: "charge", loaded: "chargé", loading: "chargement",
  save: "enregistrer", saves: "enregistre", saved: "enregistré", saving: "enregistrement",
  store: "stocker", stores: "stocke", stored: "stocké", storing: "stockage", storage: "stockage",
  sync: "synchroniser", syncs: "synchronise", synced: "synchronisé", syncing: "synchronisation", synchronize: "synchroniser",
  serve: "servir", serves: "sert", served: "servi", serving: "service",
  share: "partager", shares: "partage", shared: "partagé", sharing: "partage",
  stream: "diffuser", streams: "diffuse", streamed: "diffusé", streaming: "diffusion",
  scan: "analyser", scans: "analyse", scanned: "analysé", scanning: "analyse",
  validate: "valider", validates: "valide", validated: "validé", validating: "validation", validation: "validation",
  verify: "vérifier", verifies: "vérifie", verified: "vérifié", verifying: "vérification", verification: "vérification",
  check: "vérifier", checks: "vérifie", checked: "vérifié", checking: "vérification",
  audit: "auditer", audits: "audite", audited: "audité", auditing: "audit",
  secure: "sécuriser", secures: "sécurise", secured: "sécurisé", securing: "sécurisation", security: "sécurité",
  protect: "protéger", protects: "protège", protected: "protégé", protecting: "protection", protection: "protection",
  detect: "détecter", detects: "détecte", detected: "détecté", detecting: "détection", detection: "détection",
  prevent: "empêcher", prevents: "empêche", prevented: "empêché", preventing: "prévention",
  block: "bloquer", blocks: "bloque", blocked: "bloqué", blocking: "blocage",
  allow: "autoriser", allows: "autorise", allowed: "autorisé", allowing: "autorisation",
  deny: "refuser", denies: "refuse", denied: "refusé", denying: "refus",
  route: "router", routes: "route", routed: "routé", routing: "routage",
  filter: "filtrer", filters: "filtre", filtered: "filtré", filtering: "filtrage",
  hide: "masquer", hides: "masque", hidden: "masqué", hiding: "masquage",
  show: "afficher", shows: "affiche", shown: "affiché", showing: "affichage",
  display: "afficher", displays: "affiche", displayed: "affiché",
  notify: "notifier", notifies: "notifie", notified: "notifié", notifying: "notification", notification: "notification",
  recommend: "recommander", recommends: "recommande", recommended: "recommandé", recommending: "recommandation", recommendation: "recommandation",
  compare: "comparer", compares: "compara", compared: "comparé", comparing: "comparaison",
  rank: "classer", ranks: "classe", ranked: "classé", ranking: "classement",
  score: "noter", scores: "note", scored: "noté", scoring: "notation",
  rate: "évaluer", rates: "évalue", rated: "évalué", rating: "évaluation",
  estimate: "estimer", estimates: "estime", estimated: "estimé", estimating: "estimation", estimation: "estimation",
  calculate: "calculer", calculates: "calcule", calculated: "calculé", calculating: "calcul", calculation: "calcul",
  compute: "calculer", computes: "calcule", computed: "calculé", computing: "calcul",
  plan: "planifier", plans: "planifie", planned: "planifié", planning: "planification",
  design: "concevoir", designs: "conçoit", designed: "conçu", designing: "conception",
  configure: "configurer", configures: "configure", configured: "configuré", configuring: "configuration", configuration: "configuration",
  register: "enregistrer", registers: "enregistre", registered: "enregistré", registering: "enregistrement", registration: "enregistrement",
  authenticate: "authentifier", authenticates: "authentifie", authenticated: "authentifié", authenticating: "authentification", authentication: "authentification",
  authorize: "autoriser", authorizes: "autorise", authorized: "autorisé", authorizing: "autorisation",
  publish: "publier", publishes: "publie", published: "publié", publishing: "publication",
  submit: "soumettre", submits: "soumet", submitted: "soumis", submitting: "soumission",
  claim: "revendiquer", claims: "revendique", claimed: "revendiqué", claiming: "revendication",
  hire: "embaucher", hires: "embauche", hired: "embauché", hiring: "embauche",
  pay: "payer", pays: "paie", paid: "payé", paying: "paiement", payment: "paiement",
  settle: "régler", settles: "règle", settled: "réglé", settling: "règlement",
  buy: "acheter", buys: "achète", bought: "acheté", buying: "achat",
  sell: "vendre", sells: "vend", sold: "vendu", selling: "vente",
  rent: "louer", rents: "loue", rented: "loué", renting: "location",
  trade: "échanger", trades: "échange", traded: "échangé", trading: "négociation",
  vote: "voter", votes: "vote", voted: "voté", voting: "vote",
  decide: "décider", decides: "décide", decided: "décidé", deciding: "décision", decision: "décision",
  coordinate: "coordonner", coordinates: "coordonne", coordinated: "coordonné", coordinating: "coordination", coordination: "coordination",
  collaborate: "collaborer", collaborates: "collabore", collaborated: "collaboré", collaborating: "collaboration", collaboration: "collaboration",
  negotiate: "négocier", negotiates: "négocie", negotiated: "négocié", negotiating: "négociation",
  invoke: "invoquer", invokes: "invoque", invoked: "invoqué", invoking: "invocation",
  call: "appeler", calls: "appelle", called: "appelé", calling: "appel",
  chat: "discuter", chats: "discussion", chatted: "discuté", chatting: "discussion",
  talk: "parler", talks: "parle", talked: "parlé", talking: "discussion",
  speak: "parler", speaks: "parle", spoken: "parlé", speaking: "prise de parole",
  listen: "écouter", listens: "écoute", listened: "écouté", listening: "écoute",
  watch: "regarder", watches: "regarde", watched: "regardé", watching: "regarder",
  play: "jouer", plays: "joue", played: "joué", playing: "lecture",
  record: "enregistrer", records: "enregistre", recorded: "enregistré", recording: "enregistrement",
  transcribe: "transcrire", transcribes: "transcrit", transcribed: "transcrit", transcribing: "transcription",
  summarize: "résumer", summarizes: "résume", summarized: "résumé", summarizing: "résumé", summary: "résumé",
  translate: "traduire", translates: "traduit", translated: "traduit", translating: "traduction",
  explain: "expliquer", explains: "explique", explained: "expliqué", explaining: "explication",
  describe: "décrire", describes: "décrit", described: "décrit", describing: "description", description: "description",
  identify: "identifier", identifies: "identifie", identified: "identifié", identifying: "identification",
  classify: "classer", classifies: "classe", classified: "classé", classifying: "classification", classification: "classification",
  categorize: "catégoriser", categorizes: "catégorise", categorized: "catégorisé", categorizing: "catégorisation", category: "catégorie",
  tag: "étiqueter", tags: "étiquette", tagged: "étiqueté", tagging: "étiquetage",
  label: "étiqueter", labels: "étiquette", labelled: "étiqueté", labelling: "étiquetage",
  mark: "marquer", marks: "marque", marked: "marqué", marking: "marquage",
  annotate: "annoter", annotates: "annote", annotated: "annoté", annotating: "annotation", annotation: "annotation",
  highlight: "mettre en évidence", highlights: "met en évidence", highlighted: "mis en évidence",
  select: "sélectionner", selects: "sélectionne", selected: "sélectionné", selecting: "sélection", selection: "sélection",
  choose: "choisir", chooses: "choisit", chosen: "choisi", choosing: "choix",
  pick: "choisir", picks: "choisit", picked: "choisi", picking: "choix",
  add: "ajouter", adds: "ajoute", added: "ajouté", adding: "ajout",
  remove: "supprimer", removes: "supprime", removed: "supprimé", removing: "suppression",
  delete: "supprimer", deletes: "supprime", deleted: "supprimé", deleting: "suppression",
  update: "mettre à jour", updates: "met à jour", updated: "mis à jour", updating: "mise à jour",
  insert: "insérer", inserts: "insère", inserted: "inséré", inserting: "insertion",
  replace: "remplacer", replaces: "remplace", replaced: "remplacé", replacing: "remplacement",
  merge: "fusionner", merges: "fusionne", merged: "fusionné", merging: "fusion",
  split: "diviser", splits: "divise", split: "divisé", splitting: "division",
  combine: "combiner", combines: "combine", combined: "combiné", combining: "combinaison",
  join: "rejoindre", joins: "rejoint", joined: "rejoint", joining: "jonction",
  link: "lier", links: "lie", linked: "lié", linking: "liaison",
  attach: "attacher", attaches: "attache", attached: "attaché", attaching: "attachement",
  detach: "détacher", detaches: "détache", detached: "détaché", detaching: "détachement",
  bind: "lier", binds: "lie", bound: "lié", binding: "liaison",
  embed: "intégrer", embeds: "intègre", embedded: "intégré", embedding: "intégration",
  include: "inclure", includes: "inclut", included: "inclus", including: "y compris",
  exclude: "exclure", excludes: "exclut", excluded: "exclu", excluding: "à l'exception de",
  contain: "contenir", contains: "contient", contained: "contenu", containing: "contenant",
  wrap: "envelopper", wraps: "enveloppe", wrapped: "enveloppé", wrapping: "enveloppement",
  expose: "exposer", exposes: "expose", exposed: "exposé", exposing: "exposition",
  extract: "extraire", extracts: "extrait", extracted: "extrait", extracting: "extraction",
  parse: "analyser", parses: "analyse", parsed: "analysé", parsing: "analyse",
  index: "indexer", indexes: "indexe", indexed: "indexé", indexing: "indexation",
  cache: "mettre en cache", caches: "met en cache", cached: "en cache", caching: "mise en cache",
  optimize: "optimiser", optimizes: "optimise", optimized: "optimisé", optimizing: "optimisation", optimisation: "optimisation",
  improve: "améliorer", improves: "améliore", improved: "amélioré", improving: "amélioration",
  enhance: "améliorer", enhances: "améliore", enhanced: "amélioré", enhancing: "amélioration",
  refine: "affiner", refines: "affine", refined: "affiné", refining: "affinage",
  upgrade: "mettre à niveau", upgrades: "met à niveau", upgraded: "mis à niveau", upgrading: "mise à niveau",
  scale: "mettre à l'échelle", scales: "met à l'échelle", scaled: "mis à l'échelle", scaling: "mise à l'échelle",
  expand: "étendre", expands: "étend", expanded: "étendu", expanding: "expansion",
  reduce: "réduire", reduces: "réduit", reduced: "réduit", reducing: "réduction",
  minimize: "minimiser", minimizes: "minimise", minimized: "minimisé", minimizing: "minimisation",
  maximize: "maximiser", maximizes: "maximise", maximized: "maximisé", maximizing: "maximisation",
  limit: "limiter", limits: "limite", limited: "limité", limiting: "limitation",
  enforce: "appliquer", enforces: "applique", enforced: "appliqué", enforcing: "application",
  apply: "appliquer", applies: "applique", applied: "appliqué", applying: "application",
  implement: "implémenter", implements: "implémente", implemented: "implémenté", implementing: "implémentation", implementation: "implémentation",
  develop: "développer", develops: "développe", developed: "développé", developing: "développement",
  test: "tester", tests: "teste", tested: "testé", testing: "test",
  debug: "déboguer", debugs: "débogue", debugged: "débogué", debugging: "débogage",
  simulate: "simuler", simulates: "simule", simulated: "simulé", simulating: "simulation", simulation: "simulation",
  visualize: "visualiser", visualizes: "visualise", visualized: "visualisé", visualizing: "visualisation", visualization: "visualisation",
  draw: "dessiner", draws: "dessine", drew: "a dessiné", drawn: "dessiné", drawing: "dessin",
  paint: "peindre", paints: "peint", painted: "peint", painting: "peinture",
  sketch: "esquisser", sketches: "esquisse", sketched: "esquissé", sketching: "esquisse",
  diagram: "diagramme", diagrams: "diagrammes",
  chart: "graphique", charts: "graphiques",
  graph: "graphe", graphs: "graphes",
  image: "image", images: "images",
  photo: "photo", photos: "photos",
  picture: "image", pictures: "images",
  video: "vidéo", videos: "vidéos",
  audio: "audio",
  sound: "son", sounds: "sons",
  music: "musique",
  song: "chanson", songs: "chansons",
  album: "album", albums: "albums",
  playlist: "playlist", playlists: "playlists",
  movie: "film", movies: "films",
  film: "film", films: "films",
  tv: "télé",
  show: "émission",
  book: "livre", books: "livres",
  library: "bibliothèque", libraries: "bibliothèques",
  document: "document", documents: "documents",
  file: "fichier", files: "fichiers",
  folder: "dossier", folders: "dossiers",
  directory: "répertoire", directories: "répertoires",
  database: "base de données", databases: "bases de données",
  table: "table", tables: "tables",
  row: "ligne", rows: "lignes",
  column: "colonne", columns: "colonnes",
  record: "enregistrement", records: "enregistrements",
  field: "champ", fields: "champs",
  schema: "schéma", schemas: "schémas",
  data: "données",
  dataset: "jeu de données", datasets: "jeux de données",
  metadata: "métadonnées",
  information: "informations",
  content: "contenu",
  text: "texte",
  code: "code",
  script: "script", scripts: "scripts",
  function: "fonction", functions: "fonctions",
  method: "méthode", methods: "méthodes",
  class: "classe", classes: "classes",
  object: "objet", objects: "objets",
  module: "module", modules: "modules",
  package: "paquet", packages: "paquets",
  framework: "framework",
  tool: "outil", tools: "outils",
  server: "serveur", servers: "serveurs",
  client: "client", clients: "clients",
  service: "service", services: "services",
  app: "application", apps: "applications", application: "application", applications: "applications",
  plugin: "plugin", plugins: "plugins",
  extension: "extension", extensions: "extensions",
  component: "composant", components: "composants",
  widget: "widget", widgets: "widgets",
  model: "modèle", models: "modèles",
  agent: "agent", agents: "agents",
  assistant: "assistant", assistants: "assistants",
  bot: "bot", bots: "bots",
  persona: "persona", personas: "personas",
  user: "utilisateur", users: "utilisateurs",
  account: "compte", accounts: "comptes",
  profile: "profil", profiles: "profils",
  session: "session", sessions: "sessions",
  token: "jeton", tokens: "jetons",
  key: "clé", keys: "clés",
  credential: "identifiant", credentials: "identifiants",
  permission: "permission", permissions: "permissions",
  role: "rôle", roles: "rôles",
  policy: "politique", policies: "politiques",
  rule: "règle", rules: "règles",
  config: "configuration",
  setting: "paramètre", settings: "paramètres",
  option: "option", options: "options",
  parameter: "paramètre", parameters: "paramètres",
  environment: "environnement", environments: "environnements",
  platform: "plateforme", platforms: "plateformes",
  system: "système", systems: "systèmes",
  network: "réseau", networks: "réseaux",
  node: "nœud", nodes: "nœuds",
  cluster: "cluster", clusters: "clusters",
  endpoint: "point de terminaison", endpoints: "points de terminaison",
  link: "lien", links: "liens",
  website: "site web", websites: "sites web",
  webpage: "page web", webpages: "pages web",
  web: "web",
  page: "page", pages: "pages",
  site: "site",
  domain: "domaine", domains: "domaines",
  host: "hôte", hosts: "hôtes",
  hosting: "hébergement",
  cloud: "cloud",
  local: "local",
  remote: "distant",
  embedded: "embarqué",
  mobile: "mobile",
  desktop: "bureau",
  terminal: "terminal",
  command: "commande", commands: "commandes",
  gui: "interface graphique",
  interface: "interface", interfaces: "interfaces",
  repo: "dépôt", repos: "dépôts",
  repository: "dépôt", repositories: "dépôts",
  commit: "commit", commits: "commits",
  branch: "branche", branches: "branches",
  release: "version", releases: "versions",
  version: "version", versions: "versions",
  build: "build", builds: "builds",
  runtime: "environnement d'exécution",
  container: "conteneur", containers: "conteneurs",
  registry: "registre", registries: "registres",
  catalog: "catalogue", catalogs: "catalogues", catalogue: "catalogue", catalogues: "catalogues",
  marketplace: "marketplace",
  store: "magasin",
  directory: "annuaire", directories: "annuaires",
  hub: "hub",
  gateway: "passerelle", gateways: "passerelles",
  proxy: "proxy", proxies: "proxies",
  router: "routeur", routers: "routeurs",
  connector: "connecteur", connectors: "connecteurs",
  adapter: "adaptateur", adapters: "adaptateurs",
  integration: "intégration", integrations: "intégrations",
  skill: "compétence", skills: "compétences",
  workflow: "flux de travail", workflows: "flux de travail",
  pipeline: "pipeline", pipelines: "pipelines",
  job: "tâche", jobs: "tâches",
  task: "tâche", tasks: "tâches",
  queue: "file d'attente", queues: "files d'attente",
  worker: "worker", workers: "workers",
  schedule: "planifier", schedules: "planifie", scheduled: "planifié", scheduling: "planification",
  event: "événement", events: "événements",
  trigger: "déclencheur", triggers: "déclenche", triggered: "déclenché", triggering: "déclenchement",
  hook: "hook", hooks: "hooks",
  callback: "rappel", callbacks: "rappels",
  message: "message", messages: "messages",
  conversation: "conversation", conversations: "conversations",
  prompt: "invite", prompts: "invites",
  response: "réponse", responses: "réponses",
  request: "requête", requests: "requêtes",
  output: "sortie", outputs: "sorties",
  input: "entrée", inputs: "entrées",
  result: "résultat", results: "résultats",
  error: "erreur", errors: "erreurs",
  warning: "avertissement", warnings: "avertissements",
  log: "journal", logs: "journaux",
  metric: "métrique", metrics: "métriques",
  alert: "alerte", alerts: "alertes",
  report: "rapport", reports: "rapports",
  dashboard: "tableau de bord", dashboards: "tableaux de bord",
  analytics: "analytique",
  insight: "perspective", insights: "perspectives",
  overview: "aperçu",
  guide: "guide", guides: "guides",
  tutorial: "tutoriel", tutorials: "tutoriels",
  documentation: "documentation", docs: "docs",
  example: "exemple", examples: "exemples",
  sample: "exemple", samples: "exemples",
  template: "modèle", templates: "modèles",
  demo: "démo", demos: "démos",
  source: "source", sources: "sources",
  official: "officiel",
  community: "communauté",
  public: "public",
  private: "privé",
  open: "ouvert",
  closed: "fermé",
  free: "gratuit",
  paid: "payant",
  premium: "premium",
  trial: "essai",
  subscription: "abonnement", subscriptions: "abonnements",
  plan: "forfait", plans: "forfaits",
  pricing: "tarification",
  price: "prix", prices: "prix",
  cost: "coût", costs: "coûts",
  fee: "frais", fees: "frais",
  tier: "niveau", tiers: "niveaux",
  feature: "fonctionnalité", features: "fonctionnalités",
  capability: "capacité", capabilities: "capacités",
  benefit: "avantage", benefits: "avantages",
  usage: "utilisation",
  scenario: "scénario", scenarios: "scénarios",
  problem: "problème", problems: "problèmes",
  solution: "solution", solutions: "solutions",
  issue: "problème", issues: "problèmes",
  bug: "bug", bugs: "bugs",
  fix: "correctif", fixes: "corrige", fixed: "corrigé", fixing: "correction",
  limitation: "limitation", limitations: "limitations",
  constraint: "contrainte", constraints: "contraintes",
  requirement: "exigence", requirements: "exigences",
  dependency: "dépendance", dependencies: "dépendances",
  compatibility: "compatibilité",
  legacy: "ancien",
  modern: "moderne",
  new: "nouveau",
  old: "ancien",
  latest: "dernier",
  stable: "stable",
  beta: "bêta",
  alpha: "alpha",
  experimental: "expérimental",
  development: "développement",
  staging: "préproduction",
  live: "en direct",
  ready: "prêt",
  available: "disponible",
  unavailable: "indisponible",
  active: "actif", inactive: "inactif",
  enabled: "activé", disabled: "désactivé",
  deprecated: "déprécié",
  optional: "optionnel",
  required: "requis",
  recommended: "recommandé",
  default: "par défaut",
  custom: "personnalisé",
  built: "intégré",
  core: "cœur",
  main: "principal",
  primary: "principal",
  secondary: "secondaire",
  central: "central",
  global: "global",
  shared: "partagé",
  common: "commun",
  standard: "standard",
  advanced: "avancé",
  basic: "de base",
  simple: "simple",
  complex: "complexe",
  easy: "facile", easier: "plus facile", easiest: "le plus facile",
  hard: "difficile", harder: "plus difficile",
  fast: "rapide", faster: "plus rapide", fastest: "le plus rapide",
  slow: "lent", slower: "plus lent",
  quick: "rapide", quickly: "rapidement",
  efficient: "efficace", efficiently: "efficacement",
  reliable: "fiable", reliably: "de façon fiable",
  robust: "robuste",
  secure: "sécurisé",
  safe: "sûr", safer: "plus sûr", safest: "le plus sûr",
  unstable: "instable",
  scalable: "extensible",
  flexible: "flexible",
  portable: "portable",
  lightweight: "léger",
  heavy: "lourd",
  minimal: "minimal",
  minimalist: "minimaliste",
  complete: "complet",
  comprehensive: "complet",
  partial: "partiel",
  full: "complet",
  entire: "entièrement",
  whole: "entier",
  single: "unique",
  multiple: "plusieurs",
  many: "beaucoup",
  few: "peu",
  all: "tous",
  some: "certains",
  any: "n'importe quel",
  each: "chaque",
  every: "chaque",
  other: "autre", others: "autres",
  another: "un autre",
  additional: "supplémentaire",
  extra: "supplémentaire",
  various: "divers",
  different: "différent",
  similar: "similaire",
  same: "même",
  such: "tel",
  including: "y compris",
  excluding: "à l'exception de",
  without: "sans",
  within: "dans",
  across: "à travers",
  through: "à travers",
  between: "entre",
  among: "parmi",
  from: "de",
  to: "à",
  into: "dans",
  onto: "sur",
  with: "avec",
  by: "par",
  for: "pour",
  of: "de",
  on: "sur",
  in: "dans",
  at: "à",
  and: "et",
  or: "ou",
  but: "mais",
  not: "ne pas",
  no: "non",
  yes: "oui",
  can: "peut",
  cannot: "ne peut pas",
  could: "pourrait",
  should: "devrait",
  would: "veut",
  will: "va",
  able: "capable",
  possible: "possible",
  impossible: "impossible",
  needed: "nécessaire",
  need: "besoin",
  want: "vouloir",
  help: "aider",
  via: "via",
  per: "par",
  over: "sur",
  under: "sous",
  above: "au-dessus",
  below: "en dessous",
  this: "ce",
  that: "ce",
  these: "ces",
  those: "ces",
  it: "il",
  its: "son",
  their: "leur",
  they: "ils",
  we: "nous",
  you: "vous",
  your: "votre",
  our: "notre",
  my: "mon",
  me: "moi",
  he: "il",
  she: "elle",
  one: "un",
  two: "deux",
  three: "trois",
  first: "premier",
  last: "dernier",
  next: "suivant",
  previous: "précédent",
  current: "actuel",
  recent: "récent",
  early: "tôt",
  late: "tard",
  now: "maintenant",
  today: "aujourd'hui",
  daily: "quotidien",
  weekly: "hebdomadaire",
  monthly: "mensuel",
  yearly: "annuel",
  annual: "annuel",
  hourly: "horaire",
  real: "réel",
  virtual: "virtuel",
  digital: "numérique",
  physical: "physique",
  online: "en ligne",
  offline: "hors ligne",
  native: "natif",
  cross: "multi",
  multi: "multi",
  social: "social",
  media: "médias",
  email: "e-mail", emails: "e-mails",
  mail: "courrier",
  forum: "forum", forums: "forums",
  group: "groupe", groups: "groupes",
  team: "équipe", teams: "équipes",
  organization: "organisation", organizations: "organisations",
  company: "entreprise", companies: "entreprises",
  business: "entreprise", businesses: "entreprises",
  enterprise: "entreprise",
  project: "projet", projects: "projets",
  product: "produit", products: "produits",
  type: "type", types: "types",
  kind: "genre", kinds: "genres",
  form: "formulaire", forms: "formulaires",
  format: "format", formats: "formats",
  style: "style", styles: "styles",
  theme: "thème", themes: "thèmes",
  color: "couleur", colors: "couleurs", colour: "couleur",
  size: "taille", sizes: "tailles",
  length: "longueur",
  width: "largeur",
  height: "hauteur",
  depth: "profondeur",
  area: "zone",
  region: "région", regions: "régions",
  location: "emplacement", locations: "emplacements",
  place: "endroit", places: "endroits",
  country: "pays", countries: "pays",
  city: "ville", cities: "villes",
  state: "état", states: "états",
  language: "langue", languages: "langues",
  time: "temps", times: "fois",
  date: "date", dates: "dates",
  day: "jour", days: "jours",
  week: "semaine", weeks: "semaines",
  month: "mois", months: "mois",
  year: "année", years: "années",
  hour: "heure", hours: "heures",
  minute: "minute", minutes: "minutes",
  second: "seconde", seconds: "secondes",
  morning: "matin",
  evening: "soir",
  night: "nuit",
  number: "numéro", numbers: "numéros",
  amount: "montant",
  count: "nombre",
  total: "total",
  sum: "somme",
  average: "moyenne",
  maximum: "maximum",
  minimum: "minimum",
  range: "plage",
  set: "ensemble", sets: "ensembles",
  collection: "collection", collections: "collections",
  name: "nom", names: "noms",
  title: "titre", titles: "titres",
  detail: "détail", details: "détails",
  note: "note", notes: "notes",
  comment: "commentaire", comments: "commentaires",
  review: "avis", reviews: "avis",
  rating: "note",
  status: "statut", statuses: "statuts",
  level: "niveau", levels: "niveaux",
  grade: "note", grades: "notes",
  position: "position", positions: "positions",
  order: "ordre", orders: "ordres",
  sort: "trier", sorts: "trie", sorted: "trié", sorting: "tri",
  view: "vue", views: "vues",
  window: "fenêtre", windows: "fenêtres",
  tab: "onglet", tabs: "onglets",
  panel: "panneau", panels: "panneaux",
  sidebar: "barre latérale",
  toolbar: "barre d'outils",
  menu: "menu", menus: "menus",
  button: "bouton", buttons: "boutons",
  icon: "icône", icons: "icônes",
  logo: "logo", logos: "logos",
  badge: "badge", badges: "badges",
  card: "carte", cards: "cartes",
  tile: "tuile", tiles: "tuiles",
  grid: "grille", grids: "grilles",
  layout: "mise en page",
  font: "police", fonts: "polices",
  screen: "écran", screens: "écrans",
  device: "appareil", devices: "appareils",
  phone: "téléphone", phones: "téléphones",
  tablet: "tablette", tablets: "tablettes",
  computer: "ordinateur", computers: "ordinateurs",
  laptop: "ordinateur portable",
  software: "logiciel",
  hardware: "matériel",
  firmware: "firmware",
  engine: "moteur", engines: "moteurs",
  kernel: "noyau",
  driver: "pilote", drivers: "pilotes",
  protocol: "protocole", protocols: "protocoles",
  standard: "norme", standards: "normes",
  specification: "spécification", specifications: "spécifications", spec: "spec", specs: "specs",
  syntax: "syntaxe",
  grammar: "grammaire",
  vocabulary: "vocabulaire",
  dictionary: "dictionnaire",
  process: "processus",
  step: "étape", steps: "étapes",
  stage: "étape", stages: "étapes",
  phase: "phase", phases: "phases",
  operation: "opération", operations: "opérations",
  action: "action", actions: "actions",
  activity: "activité", activities: "activités",
  change: "changement", changes: "changements", changed: "changé",
  update: "mise à jour", updates: "mises à jour",
  edit: "modifier",
  modify: "modifier", modifies: "modifie", modified: "modifié", modifying: "modification",
  adjust: "ajuster", adjusts: "ajuste", adjusted: "ajusté", adjusting: "ajustement",
  reset: "réinitialiser", resets: "réinitialise", reset: "réinitialisé",
  clear: "effacer", clears: "efface", cleared: "effacé", clearing: "effacement",
  clean: "nettoyer", cleans: "nettoie", cleaned: "nettoyé", cleaning: "nettoyage",
  format: "formater", formats: "formate", formatted: "formaté", formatting: "formatage",
  measure: "mesurer", measures: "mesure", measured: "mesuré", measuring: "mesure",
  observe: "observer", observes: "observe", observed: "observé", observing: "observation",
  inspect: "inspecter", inspects: "inspecte", inspected: "inspecté", inspecting: "inspection",
  examine: "examiner", examines: "examine", examined: "examiné", examining: "examen",
  explore: "explorer", explores: "explore", explored: "exploré", exploring: "exploration",
  locate: "localiser", locates: "localise", located: "localisé", locating: "localisation",
  navigate: "naviguer", navigates: "navigue", navigated: "navigué", navigating: "navigation",
  surf: "naviguer",
  scroll: "défiler",
  click: "cliquer", clicks: "clique", clicked: "cliqué", clicking: "clic",
  tap: "appuyer",
  press: "appuyer", presses: "appuie", pressed: "appuyé", pressing: "appui",
  type: "taper", types: "tape", typed: "tapé", typing: "saisie",
  enter: "saisir", enters: "saisit", entered: "saisi", entering: "saisie",
  submit: "soumettre",
  upload: "téléverser", uploads: "téléverse", uploaded: "téléversé", uploading: "téléversement",
  download: "télécharger", downloads: "télécharge", downloaded: "téléchargé", downloading: "téléchargement",
  backup: "sauvegarder", backups: "sauvegardes", backed: "sauvegardé",
  restore: "restaurer", restores: "restaure", restored: "restauré", restoring: "restauration",
  migrate: "migrer", migrates: "migre", migrated: "migré", migrating: "migration",
  copy: "copier", copies: "copie", copied: "copié", copying: "copie",
  paste: "coller", pastes: "colle", pasted: "collé", pasting: "collage",
  cut: "couper", cuts: "coupe", cut: "coupé", cutting: "coupe",
  drag: "glisser", drags: "glisse", dragged: "glissé", dragging: "glissement",
  drop: "déposer", drops: "dépose", dropped: "déposé", dropping: "dépose",
  move: "déplacer", moves: "déplace", moved: "déplacé", moving: "déplacement",
  rename: "renommer", renames: "renomme", renamed: "renommé", renaming: "renommage",
  archive: "archiver", archives: "archive", archived: "archivé", archiving: "archivage",
  trash: "corbeille",
  lock: "verrouiller", locks: "verrouille", locked: "verrouillé", locking: "verrouillage",
  unlock: "déverrouiller", unlocks: "déverrouille", unlocked: "déverrouillé",
  open: "ouvrir", opens: "ouvre", opened: "ouvert", opening: "ouverture",
  close: "fermer", closes: "ferme", closed: "fermé", closing: "fermeture",
  start: "démarrer", starts: "démarre", started: "démarré", starting: "démarrage",
  stop: "arrêter", stops: "arrête", stopped: "arrêté", stopping: "arrêt",
  pause: "mettre en pause", pauses: "met en pause", paused: "en pause",
  resume: "reprendre", resumes: "reprend", resumed: "reprise",
  restart: "redémarrer", restarts: "redémarre", restarted: "redémarré",
  launch: "lancer", launches: "lance", launched: "lancé", launching: "lancement",
  perform: "effectuer", performs: "effectue", performed: "effectué", performing: "exécution",
  do: "faire", does: "fait", did: "a fait", doing: "faisant",
  make: "faire", makes: "fait", made: "fait", making: "faisant",
  act: "agir", acts: "agit", acted: "agi", acting: "action",
  work: "fonctionner", works: "fonctionne", worked: "fonctionné", working: "fonctionnement",
  operate: "fonctionner", operates: "fonctionne", operated: "fonctionné", operating: "fonctionnement",
  function: "fonctionner", functions: "fonctionne",
  handle: "gérer", handles: "gère", handled: "géré", handling: "gestion",
  offer: "offrir", offers: "offre", offered: "offert", offering: "offre",
  deliver: "livrer", delivers: "livre", delivered: "livré", delivering: "livraison",
  receive: "recevoir", receives: "reçoit", received: "reçu", receiving: "réception",
  pull: "tirer", pulls: "tire", pulled: "tiré", pulling: "tirage",
  push: "pousser", pushes: "pousse", pushed: "poussé", pushing: "poussée",
  obtain: "obtenir", obtains: "obtient", obtained: "obtenu", obtaining: "obtention",
  acquire: "acquérir", acquires: "acquiert", acquired: "acquis", acquiring: "acquisition",
  collect: "collecter", collects: "collecte", collected: "collecté", collecting: "collecte",
  gather: "rassembler", gathers: "rassemble", gathered: "rassemblé", gathering: "rassemblement",
  aggregate: "agréger", aggregates: "agrège", aggregated: "agrégé", aggregating: "agrégation",
  compile: "compiler", compiles: "compile", compiled: "compilé", compiling: "compilation",
  transform: "transformer", transforms: "transforme", transformed: "transformé", transforming: "transformation",
  express: "exprimer", expresses: "exprime", expressed: "exprimé", expressing: "expression",
  encode: "encoder", encodes: "encode", encoded: "encodé", encoding: "encodage",
  decode: "décoder", decodes: "décode", decoded: "décodé", decoding: "décodage",
  encrypt: "chiffrer", encrypts: "chiffre", encrypted: "chiffré", encrypting: "chiffrement",
  decrypt: "déchiffrer", decrypts: "déchiffre", decrypted: "déchiffré", decrypting: "déchiffrement",
  sign: "signer", signs: "signe", signed: "signé", signing: "signature",
  approve: "approuver", approves: "approuve", approved: "approuvé", approving: "approbation",
  reject: "rejeter", rejects: "rejette", rejected: "rejeté", rejecting: "rejet",
  accept: "accepter", accepts: "accepte", accepted: "accepté", accepting: "acceptation",
  cancel: "annuler", cancels: "annule", cancelled: "annulé", cancelling: "annulation",
  abort: "interrompre", aborts: "interrompt", aborted: "interrompu",
  finish: "terminer", finishes: "termine", finished: "terminé", finishing: "fin",
  complete: "compléter", completes: "complète", completed: "complété", completing: "complétion",
  fail: "échouer", fails: "échoue", failed: "échoué", failing: "échec",
  succeed: "réussir", succeeds: "réussit", succeeded: "réussi", succeeding: "réussite",
  pass: "réussir",
  win: "gagner", wins: "gagne", won: "gagné", winning: "victoire",
  lose: "perdre", loses: "perd", lost: "perdu", losing: "perte",
  worsen: "aggraver", worsens: "aggrave", worsened: "aggravé",
  break: "casser", breaks: "casse", broke: "a cassé", broken: "cassé", breaking: "cassure",
  trace: "tracer", traces: "trace", traced: "tracé", tracing: "traçage",
  profile: "profiler", profiles: "profile", profiled: "profilé", profiling: "profilage",
  benchmark: "évaluer", benchmarks: "évalue", benchmarked: "évalué",
  evaluate: "évaluer", evaluates: "évalue", evaluated: "évalué", evaluating: "évaluation",
  assess: "évaluer", assesses: "évalue", assessed: "évalué", assessing: "évaluation",
  quantify: "quantifier", quantifies: "quantifie", quantified: "quantifié",
  predict: "prédire", predicts: "prédit", predicted: "prédit", predicting: "prédiction",
  forecast: "prévoir", forecasts: "prévoit", forecasted: "prévu", forecasting: "prévision",
  suggest: "suggérer", suggests: "suggère", suggested: "suggéré", suggesting: "suggestion",
  propose: "proposer", proposes: "propose", proposed: "proposé", proposing: "proposition",
  tell: "dire", tells: "dit", told: "a dit", telling: "disant",
  ask: "demander", asks: "demande", asked: "a demandé", asking: "demandant",
  request: "demander", requests: "demande", requested: "demandé", requesting: "demande",
  question: "question", questions: "questions",
  answer: "répondre", answers: "répond", answered: "répondu", answering: "réponse",
  reply: "répondre", replies: "répond", replied: "répondu", replying: "réponse",
  respond: "répondre", responds: "répond", responded: "répondu", responding: "réponse",
  confirm: "confirmer", confirms: "confirme", confirmed: "confirmé", confirming: "confirmation",
  think: "penser", thinks: "pense", thought: "a pensé", thinking: "pensée",
  know: "savoir", knows: "sait", knew: "savait", known: "connu", knowing: "sachant",
  understand: "comprendre", understands: "comprend", understood: "a compris", understanding: "compréhension",
  learn: "apprendre", learns: "apprend", learned: "appris", learning: "apprentissage",
  teach: "enseigner", teaches: "enseigne", taught: "a enseigné", teaching: "enseignement",
  train: "entraîner", trains: "entraîne", trained: "entraîné", training: "entraînement",
  tune: "régler", tunes: "règle", tuned: "réglé", tuning: "réglage",
  calibrate: "étalonner", calibrates: "étalonne", calibrated: "étalonné",
  prepare: "préparer", prepares: "prépare", prepared: "préparé", preparing: "préparation",
  init: "init",
  initialize: "initialiser", initializes: "initialise", initialized: "initialisé", initializing: "initialisation",
  boot: "démarrer", boots: "démarre", booted: "démarré",
  quit: "quitter", quits: "quitte", quit: "quitté", quitting: "quit",
  exit: "quitter", exits: "quitte", exited: "quitté", exiting: "sortie",
  terminate: "terminer", terminates: "termine", terminated: "terminé",
  kill: "tuer", kills: "tue", killed: "tué", killing: "tuée",
  crash: "planter", crashes: "plante", crashed: "planté", crashing: "plantage",
  hang: "se bloquer", hangs: "se bloque", hanged: "bloqué",
  freeze: "geler", freezes: "gèle", froze: "a gelé", frozen: "gelé", freezing: "gel",
  timeout: "délai dépassé",
  wait: "attendre", waits: "attend", waited: "attendu", waiting: "attente",
  sleep: "dormir", sleeps: "dort", slept: "a dormi",
  delay: "retarder", delays: "retarde", delayed: "retardé", delaying: "retard",
  subscribe: "s'abonner", subscribes: "s'abonne", subscribed: "abonné", subscribing: "abonnement",
  publish: "publier",
  broadcast: "diffuser", broadcasts: "diffuse", broadcasted: "diffusé",
  ping: "ping", pings: "ping", pinged: "pingé",
  poll: "interroger", polls: "interroge", polled: "interrogé", polling: "interrogation",
  listen: "écouter",
  replicate: "répliquer", replicates: "réplique", replicated: "répliqué", replicating: "réplication",
  mirror: "miroir", mirrors: "reflète", mirrored: "reflété", mirroring: "mise en miroir",
  clone: "cloner", clones: "clone", cloned: "cloné", cloning: "clonage",
  fork: "fork", forks: "forks", forked: "forké",
  branch: "brancher", branches: "branche", branched: "branché",
  merge: "fusionner",
  diff: "comparer", diffs: "compare", diffed: "comparé",
  reconcile: "réconcilier", reconciles: "réconcilie", reconciled: "réconcilié",
  resolve: "résoudre", resolves: "résout", resolved: "résolu", resolving: "résolution",
  conflict: "conflit", conflicts: "conflits",
  revise: "réviser", revises: "révise", revised: "révisé", revising: "révision",
  amend: "amender", amends: "amende", amended: "amendé", amending: "amendement",
  correct: "corriger", corrects: "corrige", corrected: "corrigé", correcting: "correction",
  tweak: "ajuster", tweaks: "ajuste", tweaked: "ajusté", tweaking: "ajustement",
  polish: "polir", polishes: "polit", polished: "poli", polishing: "polissage",
  simplify: "simplifier", simplifies: "simplifie", simplified: "simplifié", simplifying: "simplification",
  clarify: "clarifier", clarifies: "clarifie", clarified: "clarifié", clarifying: "clarification",
  arrange: "arranger", arranges: "arrange", arranged: "arrangé", arranging: "arrangement",
  align: "aligner", aligns: "aligne", aligned: "aligné", aligning: "alignement",
  structure: "structurer", structures: "structure", structured: "structuré", structuring: "structuration",
  style: "styliser", styles: "stylise", styled: "stylisé", styling: "stylisation",
  customize: "personnaliser", customizes: "personnalise", customized: "personnalisé", customizing: "personnalisation",
  personalize: "personnaliser", personalizes: "personnalise", personalized: "personnalisé",
  adapt: "adapter", adapts: "adapte", adapted: "adapté", adapting: "adaptation",
  fit: "adapter", fits: "adapte", fitted: "adapté", fitting: "adaptation",
  match: "correspondre", matches: "correspond", matched: "correspond", matching: "correspondance",
  relate: "relier", relates: "relie", related: "lié", relating: "relation",
  associate: "associer", associates: "associe", associated: "associé", associating: "association",
  reference: "référence", references: "références", referenced: "référencé", referencing: "référencement",
  cite: "citer", cites: "cite", cited: "cité", citing: "citation",
  quote: "citer",
  mention: "mentionner", mentions: "mentionne", mentioned: "mentionné", mentioning: "mention",
  document: "documenter", documents: "documente", documented: "documenté", documenting: "documentation",
  comment: "commenter", comments: "commente", commented: "commenté", commenting: "commentaire",
  count: "compter", counts: "compte", counted: "compté", counting: "comptage",
  sum: "sommer", sums: "somme", summed: "sommé", summing: "somme",
  round: "arrondir", rounds: "arrondit", rounded: "arrondi", rounding: "arrondi",
  truncate: "tronquer", truncates: "tronque", truncated: "tronqué", truncating: "troncation",
  clip: "couper", clips: "coupe", clipped: "coupé",
  normalize: "normaliser", normalizes: "normalise", normalized: "normalisé", normalizing: "normalisation",
  standardize: "standardiser", standardizes: "standardise", standardized: "standardisé",
  unify: "unifier", unifies: "unifie", unified: "unifié", unifying: "unification",
  consolidate: "consolider", consolidates: "consolide", consolidated: "consolidé", consolidating: "consolidation",
  centralize: "centraliser", centralizes: "centralise", centralized: "centralisé", centralizing: "centralisation",
  decentralize: "décentraliser", decentralizes: "décentralise", decentralized: "décentralisé",
  distribute: "distribuer", distributes: "distribue", distributed: "distribué", distributing: "distribution",
  mount: "monter", mounts: "monte", mounted: "monté", mounting: "montage",
  unmount: "démonter", unmounts: "démonte", unmounted: "démonté",
  pair: "appairer", pairs: "appaire", paired: "appairé", pairing: "appairage",
  couple: "coupler", couples: "couple", coupled: "couplé", coupling: "couplage",
  stack: "pile", stacks: "piles", stacked: "empilé", stacking: "empilement",
  queue: "file d'attente",
  pool: "pool", pools: "pools",
  span: "couvrir", spans: "couvre", spanned: "couvert", spanning: "couverture",
  cover: "couvrir", covers: "couvre", covered: "couvert", covering: "couverture",
  supply: "fournir", supplies: "fournit", supplied: "fourni", supplying: "fourniture",
  serve: "servir",
  host: "héberger", hosts: "héberge", hosted: "hébergé", hosting: "hébergement",
  administer: "administrer", administers: "administre", administered: "administré", administering: "administration",
  supervise: "superviser", supervises: "supervise", supervised: "supervisé", supervising: "supervision",
  govern: "gouverner", governs: "gouverne", governed: "gouverné", governing: "gouvernance",
  command: "commander", commands: "commande", commanded: "commandé", commanding: "commandement",
  direct: "diriger", directs: "dirige", directed: "dirigé", directing: "direction",
  lead: "diriger", leads: "dirige", led: "a dirigé", leading: "direction",
  guide: "guider", guides: "guide", guided: "guidé", guiding: "guidage",
  drive: "piloter", drives: "pilote", drove: "a piloté", driven: "piloté", driving: "pilotage",
  power: "alimenter", powers: "alimente", powered: "alimenté", powering: "alimentation",
  fuel: "alimenter",
  feed: "alimenter", feeds: "alimente", fed: "alimenté", feeding: "alimentation",
  see: "voir", sees: "voit", saw: "a vu", seen: "vu", seeing: "voyant",
  watch: "regarder",
  inspect: "inspecter",
  examine: "examiner",
  audit: "auditer",
  review: "examiner", reviews: "examine", reviewed: "examiné", reviewing: "examen",
  moderate: "modérer", moderates: "modère", moderated: "modéré", moderating: "modération",
  curate: "organiser", curates: "organise", curated: "organisé", curating: "organisation",
  synthesize: "synthétiser", synthesizes: "synthétise", synthesized: "synthétisé",
  // adjectives / nouns extra
  curated: "organisée",
  hosted: "hébergé",
  embedded: "embarqué",
  synthetic: "synthétique",
  typed: "typé",
  raw: "brut",
  clean: "propre",
  dirty: "sale",
  valid: "valide",
  invalid: "invalide",
  correct: "correct",
  accurate: "précis",
  precise: "précis",
  exact: "exact",
  empty: "vide",
  null: "nul",
  both: "les deux",
  either: "l'un ou l'autre",
  neither: "ni l'un ni l'autre",
  high: "élevé",
  low: "bas",
  deep: "profond",
  shallow: "peu profond",
  wide: "large",
  narrow: "étroit",
  thick: "épais",
  thin: "mince",
  strong: "fort",
  weak: "faible",
  powerful: "puissant",
  smart: "intelligent",
  intelligent: "intelligent",
  active: "actif",
  visible: "visible",
  hidden: "masqué",
  dedicated: "dédié",
  reserved: "réservé",
  busy: "occupé",
  cheap: "bon marché",
  expensive: "cher",
  affordable: "abordable",
  costly: "coûteux",
  large: "grand",
  small: "petit",
  big: "grand",
  tiny: "minuscule",
  huge: "énorme",
  long: "long",
  short: "court",
  good: "bon",
  bad: "mauvais",
  better: "mieux",
  best: "le meilleur",
  worst: "le pire",
  important: "important",
  useful: "utile",
  useless: "inutile",
  relevant: "pertinent",
  irrelevant: "non pertinent",
  popular: "populaire",
  uncommon: "peu commun",
  rare: "rare",
  common: "commun",
  special: "spécial",
  general: "général",
  specific: "spécifique",
  particular: "particulier",
  normal: "normal",
  abnormal: "anormal",
  positive: "positif",
  negative: "négatif",
  true: "vrai",
  false: "faux",
  human: "humain",
  machine: "machine",
  artificial: "artificielle",
  autonomous: "autonome",
  automated: "automatisé",
  manual: "manuel",
  automatic: "automatique",
  interactive: "interactif",
  static: "statique",
  dynamic: "dynamique",
  constant: "constante",
  variable: "variable",
  public: "public",
  direct: "direct",
  indirect: "indirect",
  external: "externe",
  internal: "interne",
  local: "local",
  global: "global",
  central: "central",
  distributed: "distribué",
  centralized: "centralisé",
  parallel: "parallèle",
  concurrent: "concurrent",
  async: "asynchrone",
  synchronous: "synchrone",
  sequential: "séquentiel",
  serial: "sériel",
  hybrid: "hybride",
  live: "en direct",
  instant: "instantané",
  immediate: "immédiat",
  rapid: "rapide",
  strong: "fort",
  secure: "sécurisé",
  privacy: "confidentialité",
  safety: "sécurité",
  compliance: "conformité",
  regulation: "régulation", regulations: "régulations",
  governance: "gouvernance",
  risk: "risque", risks: "risques",
  threat: "menace", threats: "menaces",
  vulnerability: "vulnérabilité", vulnerabilities: "vulnérabilités",
  exploit: "exploit", exploits: "exploits",
  attack: "attaque", attacks: "attaques",
  defense: "défense", defenses: "défenses",
  detection: "détection",
  prevention: "prévention",
  mitigation: "atténuation", mitigations: "atténuations",
  recovery: "récupération",
  resilience: "résilience",
  availability: "disponibilité",
  uptime: "disponibilité",
  latency: "latence",
  throughput: "débit",
  bandwidth: "bande passante",
  speed: "vitesse", speeds: "vitesses",
  volume: "volume", volumes: "volumes",
  capacity: "capacité", capacities: "capacités",
  quota: "quota", quotas: "quotas",
  charge: "facturer", charges: "facture", charged: "facturé", charging: "facturation",
  bill: "facturer", bills: "facture", billed: "facturé", billing: "facturation",
  invoice: "facture", invoices: "factures",
  refund: "remboursement", refunds: "remboursements",
  credit: "crédit", credits: "crédits",
  balance: "solde", balances: "soldes",
  wallet: "portefeuille", wallets: "portefeuilles",
  transaction: "transaction", transactions: "transactions",
  transfer: "transfert", transfers: "transferts",
  exchange: "échange", exchanges: "échanges",
  market: "marché", markets: "marchés",
  order: "commande", orders: "commandes",
  portfolio: "portefeuille",
  asset: "actif", assets: "actifs",
  revenue: "revenu", revenues: "revenus",
  profit: "profit", profits: "profits",
  loss: "perte", losses: "pertes",
  gain: "gain", gains: "gains",
  income: "revenu",
  expense: "dépense", expenses: "dépenses",
  budget: "budget", budgets: "budgets",
  strategy: "stratégie", strategies: "stratégies",
  goal: "objectif", goals: "objectifs",
  objective: "objectif", objectives: "objectifs",
  target: "cible", targets: "cibles",
  metric: "métrique",
  indicator: "indicateur", indicators: "indicateurs",
  benchmark: "référence", benchmarks: "références",
  baseline: "référence",
  trend: "tendance", trends: "tendances",
  pattern: "modèle", patterns: "modèles",
  anomaly: "anomalie", anomalies: "anomalies",
  outlier: "valeur aberrante", outliers: "valeurs aberrantes",
  prediction: "prédiction", predictions: "prédictions",
  projection: "projection", projections: "projections",
  simulation: "simulation", simulations: "simulations",
  concept: "concept", concepts: "concepts",
  idea: "idée", ideas: "idées",
  thought: "pensée", thoughts: "pensées",
  notion: "notion", notions: "notions",
  principle: "principe", principles: "principes",
  law: "loi", laws: "lois",
  formula: "formule", formulas: "formules",
  equation: "équation", equations: "équations",
  algorithm: "algorithme", algorithms: "algorithmes",
  technique: "technique", techniques: "techniques",
  approach: "approche", approaches: "approches",
  procedure: "procédure", procedures: "procédures",
  condition: "condition", conditions: "conditions",
  state: "état", states: "états",
  mode: "mode", modes: "modes",
  argument: "argument", arguments: "arguments",
  value: "valeur", values: "valeurs",
  variable: "variable", variables: "variables",
  constant: "constante", constants: "constantes",
  property: "propriété", properties: "propriétés",
  attribute: "attribut", attributes: "attributs",
  identifier: "identifiant", identifiers: "identifiants",
  uuid: "UUID",
  path: "chemin", paths: "chemins",
  route: "route", routes: "routes",
  address: "adresse", addresses: "adresses",
  port: "port", ports: "ports",
  subdomain: "sous-domaine", subdomains: "sous-domaines",
  scheme: "schéma", schemes: "schémas",
  query: "requête",
  offset: "décalage", offsets: "décalages",
  bucket: "bucket", buckets: "buckets",
  blob: "blob",
  stream: "flux", streams: "flux",
  materialized: "matérialisée",
  tree: "arbre", trees: "arbres",
  edge: "arête", edges: "arêtes",
  vertex: "sommet", vertices: "sommets",
  relationship: "relation", relationships: "relations",
  relation: "relation",
  association: "association",
  mapping: "correspondance", mappings: "correspondances",
  join: "jointure", joins: "jointures",
  union: "union", unions: "unions",
  intersection: "intersection", intersections: "intersections",
  difference: "différence", differences: "différences",
  aggregate: "agrégat", aggregates: "agrégats",
  instance: "instance", instances: "instances",
  shape: "forme", shapes: "formes",
  dimension: "dimension", dimensions: "dimensions",
  scale: "échelle", scales: "échelles",
  unit: "unité", units: "unités",
  string: "chaîne", strings: "chaînes",
  boolean: "booléen", booleans: "booléens",
  integer: "entier", integers: "entiers",
  float: "nombre flottant", floats: "nombres flottants",
  array: "tableau", arrays: "tableaux",
  map: "carte", maps: "cartes",
  serialized: "sérialisé",
  deserialized: "désérialisé",
  converted: "converti",
  formatted: "formaté",
  normalized: "normalisé",
  escaped: "échappé",
  localized: "localisé",
  internationalized: "internationalisé",
  // common README nouns not yet covered
  list: "liste",
  collection: "collection",
  directory: "annuaire",
  marketplace: "marketplace",
  catalog: "catalogue",
  hub: "hub",
  gateway: "passerelle",
  proxy: "proxy",
  connector: "connecteur",
  adapter: "adaptateur",
  integration: "intégration",
  skill: "compétence",
  workflow: "flux de travail",
  pipeline: "pipeline",
  job: "tâche",
  task: "tâche",
  activity: "activité",
  action: "action",
  operation: "opération",
  event: "événement",
  trigger: "déclencheur",
  condition: "condition",
  state: "état",
  status: "statut",
  flag: "drapeau",
  mode: "mode",
  option: "option",
  parameter: "paramètre",
  input: "entrée",
  output: "sortie",
  result: "résultat",
  value: "valeur",
  variable: "variable",
  constant: "constante",
  field: "champ",
  property: "propriété",
  attribute: "attribut",
  metadata: "métadonnées",
  tag: "étiquette",
  label: "étiquette",
  name: "nom",
  title: "titre",
  identifier: "identifiant",
  reference: "référence",
  link: "lien",
  url: "URL",
  uri: "URI",
  path: "chemin",
  route: "route",
  endpoint: "point de terminaison",
  address: "adresse",
  location: "emplacement",
  port: "port",
  host: "hôte",
  domain: "domaine",
  subdomain: "sous-domaine",
  protocol: "protocole",
  scheme: "schéma",
  query: "requête",
  filter: "filtre",
  sort: "tri",
  order: "ordre",
  limit: "limite",
  offset: "décalage",
  page: "page",
  size: "taille",
  count: "nombre",
  total: "total",
  data: "données",
  dataset: "jeu de données",
  database: "base de données",
  table: "table",
  row: "ligne",
  column: "colonne",
  record: "enregistrement",
  document: "document",
  file: "fichier",
  folder: "dossier",
  directory: "répertoire",
  bucket: "bucket",
  object: "objet",
  blob: "blob",
  stream: "flux",
  buffer: "tampon",
  queue: "file d'attente",
  cache: "cache",
  index: "index",
  view: "vue",
  schema: "schéma",
  model: "modèle",
  graph: "graphe",
  tree: "arbre",
  node: "nœud",
  edge: "arête",
  vertex: "sommet",
  path: "chemin",
  relationship: "relation",
  association: "association",
  mapping: "correspondance",
  join: "jointure",
  union: "union",
  intersection: "intersection",
  difference: "différence",
  aggregate: "agrégat",
  group: "groupe",
  category: "catégorie",
  type: "type",
  kind: "genre",
  class: "classe",
  instance: "instance",
  example: "exemple",
  sample: "échantillon",
  template: "modèle",
  pattern: "modèle",
  format: "format",
  structure: "structure",
  layout: "mise en page",
  form: "formulaire",
  shape: "forme",
  color: "couleur",
  size: "taille",
  dimension: "dimension",
  scale: "échelle",
  unit: "unité",
  number: "nombre",
  string: "chaîne",
  boolean: "booléen",
  integer: "entier",
  float: "nombre flottant",
  list: "liste",
  array: "tableau",
  map: "carte",
  set: "ensemble",
  dictionary: "dictionnaire",
  object: "objet",
  json: "JSON",
  xml: "XML",
  csv: "CSV",
  yaml: "YAML",
  text: "texte",
  binary: "binaire",
  raw: "brut",
  encoded: "encodé",
  decoded: "décodé",
  compressed: "compressé",
  encrypted: "chiffré",
  hashed: "haché",
  signed: "signé",
  verified: "vérifié",
  validated: "validé",
  parsed: "analysé",
  converted: "converti",
  formatted: "formaté",
  normalized: "normalisé",
  // misc
  everything: "tout",
  anything: "n'importe quoi",
  nothing: "rien",
  something: "quelque chose",
  everybody: "tout le monde",
  everyone: "tout le monde",
  somebody: "quelqu'un",
  someone: "quelqu'un",
  nobody: "personne",
  nowhere: "nulle part",
  everywhere: "partout",
  anywhere: "n'importe où",
  somewhere: "quelque part",
  here: "ici",
  there: "là",
  inside: "à l'intérieur",
  outside: "à l'extérieur",
  above: "au-dessus",
  below: "en dessous",
  top: "haut",
  bottom: "bas",
  left: "gauche",
  right: "droite",
  front: "avant",
  back: "arrière",
  center: "centre",
  middle: "milieu",
  side: "côté",
  corner: "coin",
  surface: "surface",
  boundary: "limite",
  border: "frontière",
  near: "proche",
  far: "loin",
  close: "proche",
  adjacent: "adjacent",
  around: "autour",
  nearby: "à proximité",
  before: "avant",
  after: "après",
  during: "pendant",
  while: "pendant que",
  until: "jusqu'à",
  since: "depuis",
  because: "parce que",
  though: "bien que",
  although: "bien que",
  however: "cependant",
  therefore: "par conséquent",
  thus: "ainsi",
  moreover: "de plus",
  furthermore: "en outre",
  additionally: "en outre",
  instead: "au lieu de",
  otherwise: "sinon",
  meanwhile: "pendant ce temps",
  still: "encore",
  already: "déjà",
  yet: "encore",
  again: "à nouveau",
  also: "aussi",
  too: "aussi",
  only: "seulement",
  just: "juste",
  even: "même",
  ever: "jamais",
  never: "jamais",
  always: "toujours",
  often: "souvent",
  sometimes: "parfois",
  rarely: "rarement",
  usually: "généralement",
  normally: "normalement",
  typically: "généralement",
  frequently: "fréquemment",
  occasionally: "occasionnellement",
  directly: "directement",
  indirectly: "indirectement",
  automatically: "automatiquement",
  manually: "manuellement",
  locally: "localement",
  remotely: "à distance",
  globally: "globalement",
  securely: "en toute sécurité",
  safely: "en toute sécurité",
  easily: "facilement",
  quickly: "rapidement",
  slowly: "lentement",
  efficiently: "efficacement",
  reliably: "de façon fiable",
  correctly: "correctement",
  accurately: "avec précision",
  properly: "correctement",
  simply: "simplement",
  freely: "librement",
  privately: "privément",
  publicly: "publiquement",
  officially: "officiellement",
  directly: "directement",
  separately: "séparément",
  together: "ensemble",
  apart: "à part",
  aside: "de côté",
  ahead: "devant",
  behind: "derrière",
  forward: "en avant",
  backward: "en arrière",
  upward: "vers le haut",
  downward: "vers le bas",
  inward: "vers l'intérieur",
  outward: "vers l'extérieur",
  outward: "vers l'extérieur",
  // verbs past/present helpers already mostly covered; add remaining
  lets: "permet",
  makes: "rend",
  helps: "aide",
  allows: "permet",
  provides: "fournit",
  offers: "offre",
  supports: "prend en charge",
  includes: "inclut",
  contains: "contient",
  requires: "nécessite",
  needs: "a besoin",
  uses: "utilise",
  builds: "construit",
  creates: "crée",
  generates: "génère",
  manages: "gère",
  controls: "contrôle",
  monitors: "surveille",
  tracks: "suit",
  searches: "recherche",
  finds: "trouve",
  discovers: "découvre",
  browses: "parcourt",
  views: "affiche",
  edits: "modifie",
  reads: "lit",
  writes: "écrit",
  sends: "envoie",
  receives: "reçoit",
  processes: "traite",
  analyzes: "analyse",
  converts: "convertit",
  transforms: "transforme",
  translates: "traduit",
  summarizes: "résume",
  extracts: "extrait",
  parses: "analyse",
  renders: "rend",
  displays: "affiche",
  shows: "affiche",
  presents: "présente",
  represents: "représente",
  connects: "connecte",
  integrates: "intègre",
  bridges: "relie",
  links: "lie",
  combines: "combine",
  merges: "fusionne",
  joins: "rejoint",
  unifies: "unifie",
  aggregates: "agrège",
  consolidates: "consolide",
  centralizes: "centralise",
  organizes: "organise",
  structures: "structure",
  arranges: "arrange",
  sorts: "trie",
  filters: "filtre",
  validates: "valide",
  verifies: "vérifie",
  checks: "vérifie",
  tests: "teste",
  measures: "mesure",
  computes: "calcule",
  calculates: "calcule",
  estimates: "estime",
  predicts: "prédit",
  forecasts: "prévoit",
  recommends: "recommande",
  suggests: "suggère",
  proposes: "propose",
  plans: "planifie",
  designs: "conçoit",
  develops: "développe",
  implements: "implémente",
  deploys: "déploie",
  installs: "installe",
  configures: "configure",
  sets: "définit",
  updates: "met à jour",
  upgrades: "met à niveau",
  patches: "corrige",
  fixes: "corrige",
  improves: "améliore",
  optimizes: "optimise",
  enhances: "améliore",
  refines: "affine",
  polishes: "polit",
  scales: "met à l'échelle",
  grows: "grandit",
  expands: "étend",
  extends: "étend",
  reduces: "réduit",
  minimizes: "minimise",
  maximizes: "maximise",
  simplifies: "simplifie",
  clarifies: "clarifie",
  explains: "explique",
  describes: "décrit",
  defines: "définit",
  specifies: "spécifie",
  documents: "documente",
  records: "enregistre",
  logs: "journalise",
  reports: "rapporte",
  notifies: "notifie",
  alerts: "alerte",
  warns: "avertit",
  informs: "informe",
  protects: "protège",
  secures: "sécurise",
  defends: "défend",
  encrypts: "chiffre",
  hides: "masque",
  anonymizes: "anonymise",
  redacts: "supprime",
  sanitizes: "assainit",
  cleans: "nettoie",
  purges: "purge",
  clears: "efface",
  resets: "réinitialise",
  deletes: "supprime",
  removes: "supprime",
  adds: "ajoute",
  inserts: "insère",
  appends: "ajoute",
  replaces: "remplace",
  swaps: "échange",
  switches: "bascule",
  toggles: "bascule",
  enables: "active",
  disables: "désactive",
  starts: "démarre",
  stops: "arrête",
  pauses: "met en pause",
  resumes: "reprend",
  runs: "exécute",
  executes: "exécute",
  launches: "lance",
  quits: "quitte",
  exits: "quitte",
  loads: "charge",
  saves: "enregistre",
  imports: "importe",
  exports: "exporte",
  uploads: "téléverse",
  downloads: "télécharge",
  syncs: "synchronise",
  backs: "sauvegarde",
  restores: "restaure",
  copies: "copie",
  pastes: "colle",
  cuts: "coupe",
  undoes: "annule",
  redoes: "refait",
  refreshes: "actualise",
  reloads: "recharge",
  fetches: "récupère",
  pulls: "tire",
  pushes: "pousse",
  gets: "obtient",
  puts: "met",
  posts: "publie",
  subscribes: "s'abonne",
  publishes: "publie",
  broadcasts: "diffuse",
  streams: "diffuse",
  watches: "surveille",
  listens: "écoute",
  polls: "interroge",
  triggers: "déclenche",
  automates: "automatise",
  schedules: "planifie",
  invokes: "invoque",
  calls: "appelle",
  routes: "route",
  proxies: "mandate",
  gates: "contrôle",
  governs: "gouverne",
  administers: "administre",
  supervises: "supervise",
  moderates: "modère",
  curates: "organise",
  ranks: "classe",
  rates: "évalue",
  scores: "note",
  grades: "note",
  reviews: "examine",
  audits: "audite",
  inspects: "inspecte",
  examines: "examine",
  explores: "explore",
  navigates: "navigue",
  locates: "localise",
  detects: "détecte",
  identifies: "identifie",
  classifies: "classe",
  categorizes: "catégorise",
  tags: "étiquette",
  labels: "étiquette",
  marks: "marque",
  flags: "signale",
  archives: "archive",
  locks: "verrouille",
  unlocks: "déverrouille",
  opens: "ouvre",
  closes: "ferme",
  mounts: "monte",
  unmounts: "démonte",
  attaches: "attache",
  detaches: "détache",
  binds: "lie",
  pairs: "appaire",
  couples: "couple",
  maps: "cartographie",
  relates: "relie",
  associates: "associe",
  references: "référence",
  cites: "cite",
  mentions: "mentionne",
  notes: "note",
  comments: "commente",
  annotates: "annote",
  measures: "mesure",
  counts: "compte",
  sums: "somme",
  totals: "totalise",
  averages: "moyenne",
  approximates: "approximative",
  rounds: "arrondit",
  truncates: "tronque",
  normalizes: "normalise",
  standardizes: "standardise",
  unifies: "unifie",
  consolidates: "consolide",
  centralizes: "centralise",
  decentralizes: "décentralise",
  distributes: "distribue",
  powers: "alimente",
  feeds: "alimente",
  sources: "source",
  engineers: "conçoit",
  programs: "programme",
  codes: "code",
  compiles: "compile",
  debugs: "débogue",
  ships: "expédie",
  manufactures: "fabrique",
  assembles: "assemble",
  constructs: "construit",
  tunes: "règle",
  trains: "entraîne",
  teaches: "enseigne",
  learns: "apprend",
  leads: "dirige",
  directs: "dirige",
  drives: "pilote",
  commands: "commande",
  answers: "répond",
  replies: "répond",
  responds: "répond",
  confirms: "confirme",
  accepts: "accepte",
  approves: "approuve",
  rejects: "rejette",
  denies: "refuse",
  chooses: "choisit",
  selects: "sélectionne",
  picks: "choisit",
  decides: "décide",
  determines: "détermine",
  resolves: "résout",
  solves: "résout",
  repairs: "répare",
  recovers: "récupère",
  retries: "réessaie",
  repeats: "répète",
  iterates: "itère",
  crawls: "explore",
  scrapes: "extrait",
  mines: "extrait",
  harvests: "récolte",
  collects: "collecte",
  gathers: "rassemble",
  aggregates: "agrège",
  condenses: "condense",
  expands: "développe",
  elaborates: "développe",
  details: "détaille",
  illustrates: "illustre",
  demonstrates: "démontre",
  proves: "prouve",
  assists: "assiste",
  aids: "aide",
  guides: "guide",
  prepares: "prépare",
  initializes: "initialise",
  boots: "démarre",
  crashes: "plante",
  hangs: "se bloque",
  freezes: "gèle",
  waits: "attend",
  sleeps: "dort",
  delays: "retarde",
  replicates: "réplique",
  mirrors: "reflète",
  clones: "clone",
  forks: "fork",
  branches: "branche",
  merges: "fusionne",
  reconciles: "réconcilie",
  conflicts: "conflit",
  changes: "change",
  modifies: "modifie",
  revises: "révise",
  amends: "amende",
  corrects: "corrige",
  tweaks: "ajuste",
  polishes: "polit",
  improves: "améliore",
  optimizes: "optimise",
  enhances: "améliore",
  upgrades: "met à niveau",
  extends: "étend",
  expands: "étend",
  scales: "met à l'échelle",
  grows: "grandit",
  shrinks: "réduit",
  reduces: "réduit",
  minimizes: "minimise",
  maximizes: "maximise",
  simplifies: "simplifie",
  clarifies: "clarifie",
  organizes: "organise",
  orders: "ordonne",
  aligns: "aligne",
  formats: "formate",
  structures: "structure",
  lays: "dispose",
  styles: "stylise",
  themes: "thème",
  templates: "modèle",
  customizes: "personnalise",
  personalizes: "personnalise",
  adapts: "adapte",
  adjusts: "ajuste",
  calibrates: "étalonne",
  fits: "adapte",
  matches: "correspond",
  associates: "associe",
  cites: "cite",
  mentions: "mentionne",
  documents: "documente",
  tracks: "suit",
  traces: "trace",
  measures: "mesure",
  computes: "calcule",
  estimates: "estime",
  approximates: "approximative",
  rounds: "arrondit",
  normalizes: "normalise",
  standardizes: "standardise",
};

// Heading overrides keyed by exact visible English heading text.
export const HEADING_OVERRIDES = {
  "What is MCP?": "Qu'est-ce que le MCP ?",
  "Clients": "Clients",
  "Remote Servers": "Serveurs distants",
  "Tutorials": "Tutoriels",
  "Community": "Communauté",
  "Legend": "Légende",
  "Server Implementations": "Implémentations de serveurs",
  "Aggregators": "Agrégateurs",
  "Aerospace & Astrodynamics": "Aérospatiale et astrodynamique",
  "Agreements & Coordination": "Accords et coordination",
  "Accessibility": "Accessibilité",
  "Art & Culture": "Art et culture",
  "Architecture & Design": "Architecture et conception",
  "Biology, Medicine and Bioinformatics": "Biologie, médecine et bioinformatique",
  "Browser Automation": "Automatisation de navigateur",
};

// Editorial / structural line overrides keyed by EXACT English source masked text.
// Robust across batches because the same source strings recur.
export const TEXT_OVERRIDES = {
  "A curated list of awesome Model Context Protocol (MCP) servers.":
    "Une liste organisée de serveurs Model Context Protocol (MCP) exceptionnels.",
  "@@L0@@ is an open protocol that enables AI models to securely interact with local and remote resources through standardized server implementations. This list focuses on production-ready and experimental MCP servers that extend AI capabilities through file access, database connections, API integrations, and other contextual services.":
    "@@L0@@ est un protocole ouvert qui permet aux modèles d'IA d'interagir en toute sécurité avec des ressources locales et distantes via des implémentations de serveurs standardisées. Cette liste se concentre sur les serveurs MCP prêts pour la production et expérimentaux qui étendent les capacités de l'IA via l'accès aux fichiers, les connexions aux bases de données, les intégrations d'API et d'autres services contextuels.",
  "Checkout @@L0@@ and @@L1@@.":
    "Découvrez @@L0@@ et @@L1@@.",
  "This list is for servers with a GitHub repo you install and run yourself. Looking for a hosted server you just connect to over a URL? See @@L0@@.":
    "Cette liste est destinée aux serveurs disposant d'un dépôt GitHub que vous installez et exécutez vous-même. Vous cherchez un serveur hébergé auquel vous vous connectez simplement via une URL&nbsp;? Voir @@L0@@.",
  "* 🎖️ – official implementation": "* 🎖️ – implémentation officielle",
  "* programming language": "* langage de programmation",
  "  * 🐍 – Python codebase": "  * 🐍 – base de code Python",
  "  * 📇 – TypeScript (or JavaScript) codebase": "  * 📇 – base de code TypeScript (ou JavaScript)",
  "  * 🏎️ – Go codebase": "  * 🏎️ – base de code Go",
  "  * 🦀 – Rust codebase": "  * 🦀 – base de code Rust",
  "  * #️⃣ - C# Codebase": "  * #️⃣ – base de code C#",
  "  * ☕ - Java codebase": "  * ☕ – base de code Java",
  "  * 🌊 – C/C++ codebase": "  * 🌊 – base de code C/C++",
  "  * 💎 - Ruby codebase": "  * 💎 – base de code Ruby",
  "* scope": "* portée",
  "  * ☁️ - Cloud Service": "  * ☁️ – service cloud",
  "  * 🏠 - Local Service": "  * 🏠 – service local",
  "  * 📟 - Embedded Systems": "  * 📟 – systèmes embarqués",
  "* operating system": "* système d'exploitation",
  "  * 🍎 – For macOS": "  * 🍎 – pour macOS",
  "  * 🪟 – For Windows": "  * 🪟 – pour Windows",
  "  * 🐧 - For Linux": "  * 🐧 – pour Linux",
  "> [!NOTE]": "> [!NOTE]",
  "> Confused about Local 🏠 vs Cloud ☁️?": "> Confus entre Local 🏠 et Cloud ☁️&nbsp;?",
  "> * Use local when MCP server is talking to a locally installed software, e.g. taking control over Chrome browser.":
    "> * Utilisez le local lorsque le serveur MCP communique avec un logiciel installé localement, par exemple en prenant le contrôle du navigateur Chrome.",
  "> * Use cloud when MCP server is talking to remote APIs, e.g. weather API.":
    "> * Utilisez le cloud lorsque le serveur MCP communique avec des API distantes, par exemple une API météo.",
  "> We now have a @@L0@@ that is synced with the repository.":
    "> Nous disposons maintenant d'un @@L0@@ qui est synchronisé avec le dépôt.",
  "Servers for accessing many apps and tools through a single MCP server.":
    "Serveurs permettant d'accéder à de nombreuses applications et outils via un seul serveur MCP.",
  "MCP servers for creating, coordinating, and executing agreements: commitments, escrow, and multi-party decision workflows across humans, agents, and organizations.":
    "Serveurs MCP pour créer, coordonner et exécuter des accords&nbsp;: engagements, séquestre et flux de travail de décision multi-parties entre humains, agents et organisations.",
  "Access and explore art collections, cultural heritage, and museum databases. Enables AI models to search and analyze artistic and cultural content.":
    "Accédez et explorez des collections d'art, du patrimoine culturel et des bases de données de musées. Permet aux modèles d'IA de rechercher et d'analyser du contenu artistique et culturel.",
  "Design and visualize software architecture, system diagrams, and technical documentation. Enables AI models to generate professional diagrams and architectural documentation.":
    "Concevez et visualisez l'architecture logicielle, les diagrammes système et la documentation technique. Permet aux modèles d'IA de générer des diagrammes professionnels et de la documentation architecturale.",
};