export const welcomeCopy = {
  root: {
    eyebrow: "Welcome to Awesome Site",
    title: "Less searching. More discovering.",
    intro: "Find your next tool, idea, or inspiration in community-curated open-source collections. Explore a topic, read in your language, and follow the source.",
    explore: "Explore the collections",
    start: "Find your topic",
    collections: "Hosted collections",
    topics: "Topics to explore",
    languages: "Reading languages",
    topicTitle: "Where will curiosity take you?",
    topicIntro: "Choose a starting point. Every topic leads to a collection worth exploring.",
    features: [
      { title: "Curated by communities", body: "Discover tools and resources gathered by the people who use them." },
      { title: "Read in your language", body: "Browse complete collection editions in English and nine other languages." },
      { title: "Stay close to the source", body: "Hosted editions link to pinned originals; additional repositories open on GitHub." },
    ],
  },
  "zh-CN": {
    eyebrow: "欢迎来到 Awesome Site",
    title: "少一点搜索，多一点发现。",
    intro: "在开源社区精心整理的合集中，找到下一个工具、想法或灵感。从感兴趣的主题出发，用熟悉的语言阅读，再深入探索原始仓库。",
    explore: "探索精选合集",
    start: "找到感兴趣的主题",
    collections: "站内合集",
    topics: "可探索主题",
    languages: "阅读语言",
    topicTitle: "让好奇心带你出发",
    topicIntro: "选一个起点，每个主题都通往值得探索的合集。",
    features: [
      { title: "来自社区的精选", body: "发现由实际使用者收集整理的工具与资源。" },
      { title: "用你的语言阅读", body: "浏览英语及其他九种语言的完整合集版本。" },
      { title: "始终连接原始来源", body: "站内版本链接到固定修订的原文，更多仓库可前往 GitHub 探索。" },
    ],
  },
  "zh-Hant": {
    eyebrow: "歡迎來到 Awesome Site",
    title: "少一點搜尋，多一點發現。",
    intro: "在開源社群精心整理的精選集中，找到下一個工具、想法或靈感。從感興趣的主題出發，用熟悉的語言閱讀，再深入探索原始儲存庫。",
    explore: "探索精選集",
    start: "找到感興趣的主題",
    collections: "站內精選集",
    topics: "可探索主題",
    languages: "閱讀語言",
    topicTitle: "讓好奇心帶你出發",
    topicIntro: "選一個起點，每個主題都通往值得探索的精選集。",
    features: [
      { title: "來自社群的精選", body: "發現由實際使用者收集整理的工具與資源。" },
      { title: "用你的語言閱讀", body: "瀏覽英語及其他九種語言的完整精選集版本。" },
      { title: "始終連結原始來源", body: "站內版本連結到固定修訂的原文，更多儲存庫可前往 GitHub 探索。" },
    ],
  },
  "fr-FR": {
    eyebrow: "Bienvenue sur Awesome Site",
    title: "Cherchez moins. Découvrez davantage.",
    intro: "Trouvez votre prochain outil, idée ou inspiration dans des collections open source sélectionnées par les communautés. Explorez un sujet, lisez dans votre langue et retrouvez la source.",
    explore: "Explorer les collections",
    start: "Trouver votre sujet",
    collections: "Collections hébergées",
    topics: "Sujets à explorer",
    languages: "Langues de lecture",
    topicTitle: "Où vous mènera votre curiosité ?",
    topicIntro: "Choisissez un point de départ. Chaque sujet mène à une collection à découvrir.",
    features: [
      { title: "Sélectionnées par les communautés", body: "Découvrez des outils et des ressources rassemblés par ceux qui les utilisent." },
      { title: "Lisez dans votre langue", body: "Parcourez des éditions complètes en anglais et dans neuf autres langues." },
      { title: "Gardez le lien avec la source", body: "Les éditions hébergées renvoient aux originaux à une révision fixe ; les autres dépôts s’ouvrent sur GitHub." },
    ],
  },
  "de-DE": {
    eyebrow: "Willkommen bei Awesome Site",
    title: "Weniger suchen. Mehr entdecken.",
    intro: "Finde dein nächstes Werkzeug, eine Idee oder Inspiration in Open-Source-Sammlungen aus der Community. Entdecke ein Thema, lies in deiner Sprache und folge der Quelle.",
    explore: "Sammlungen entdecken",
    start: "Dein Thema finden",
    collections: "Gehostete Sammlungen",
    topics: "Themen zum Entdecken",
    languages: "Lesesprachen",
    topicTitle: "Wohin führt dich deine Neugier?",
    topicIntro: "Wähle einen Ausgangspunkt. Jedes Thema führt zu einer spannenden Sammlung.",
    features: [
      { title: "Von Communitys zusammengestellt", body: "Entdecke Werkzeuge und Ressourcen, gesammelt von den Menschen, die sie nutzen." },
      { title: "In deiner Sprache lesen", body: "Lies vollständige Sammlungen auf Englisch und in neun weiteren Sprachen." },
      { title: "Mit der Quelle verbunden bleiben", body: "Gehostete Ausgaben verlinken festgelegte Originalversionen; weitere Repositories öffnen sich auf GitHub." },
    ],
  },
  "es-ES": {
    eyebrow: "Te damos la bienvenida a Awesome Site",
    title: "Busca menos. Descubre más.",
    intro: "Encuentra tu próxima herramienta, idea o inspiración en colecciones de código abierto seleccionadas por comunidades. Explora un tema, lee en tu idioma y consulta la fuente.",
    explore: "Explorar las colecciones",
    start: "Encuentra tu tema",
    collections: "Colecciones alojadas",
    topics: "Temas para explorar",
    languages: "Idiomas de lectura",
    topicTitle: "¿Adónde te llevará la curiosidad?",
    topicIntro: "Elige un punto de partida. Cada tema lleva a una colección que merece la pena explorar.",
    features: [
      { title: "Seleccionadas por comunidades", body: "Descubre herramientas y recursos reunidos por quienes los utilizan." },
      { title: "Lee en tu idioma", body: "Explora ediciones completas en inglés y en otros nueve idiomas." },
      { title: "Mantén el vínculo con la fuente", body: "Las ediciones alojadas enlazan a revisiones fijas de los originales; los demás repositorios se abren en GitHub." },
    ],
  },
  "ja-JP": {
    eyebrow: "Awesome Site へようこそ",
    title: "探す時間を減らし、発見を増やそう。",
    intro: "オープンソースコミュニティが厳選したコレクションから、次のツールやアイデア、ひらめきを見つけましょう。気になるトピックを選び、使い慣れた言語で読み、元のリポジトリへ進めます。",
    explore: "コレクションを探索",
    start: "気になるトピックを探す",
    collections: "サイト内のコレクション",
    topics: "探索できるトピック",
    languages: "読む言語",
    topicTitle: "好奇心の向かう先へ",
    topicIntro: "まずはトピックを選びましょう。どのトピックにも、探索する価値のあるコレクションがあります。",
    features: [
      { title: "コミュニティによる厳選", body: "実際に使っている人々が集めたツールやリソースを発見できます。" },
      { title: "使い慣れた言語で読む", body: "英語とその他9言語で、コレクションの完全版を閲覧できます。" },
      { title: "元の情報につながる", body: "サイト内の各版は固定リビジョンの原文にリンクし、その他のリポジトリは GitHub で開きます。" },
    ],
  },
  "ko-KR": {
    eyebrow: "Awesome Site에 오신 것을 환영합니다",
    title: "검색은 줄이고, 발견은 늘리세요.",
    intro: "오픈 소스 커뮤니티가 엄선한 컬렉션에서 다음 도구, 아이디어, 영감을 찾아보세요. 관심 있는 주제를 탐색하고, 익숙한 언어로 읽고, 원본 저장소까지 살펴보세요.",
    explore: "컬렉션 탐색하기",
    start: "관심 있는 주제 찾기",
    collections: "사이트 내 컬렉션",
    topics: "탐색할 주제",
    languages: "읽기 언어",
    topicTitle: "호기심을 따라 시작해 보세요",
    topicIntro: "출발점을 선택하세요. 각 주제에서 탐색할 만한 컬렉션을 만날 수 있습니다.",
    features: [
      { title: "커뮤니티가 엄선한 자료", body: "직접 사용하는 사람들이 모은 도구와 리소스를 발견하세요." },
      { title: "익숙한 언어로 읽기", body: "영어와 다른 9개 언어로 컬렉션 전체를 읽을 수 있습니다." },
      { title: "원본과 이어지는 탐색", body: "사이트 내 버전은 고정된 리비전의 원문으로 연결되며, 추가 저장소는 GitHub에서 열립니다." },
    ],
  },
  "pt-BR": {
    eyebrow: "Boas-vindas ao Awesome Site",
    title: "Menos busca. Mais descobertas.",
    intro: "Encontre sua próxima ferramenta, ideia ou inspiração em coleções de código aberto selecionadas pelas comunidades. Explore um tópico, leia no seu idioma e consulte a fonte.",
    explore: "Explorar as coleções",
    start: "Encontre seu tópico",
    collections: "Coleções hospedadas",
    topics: "Tópicos para explorar",
    languages: "Idiomas de leitura",
    topicTitle: "Aonde sua curiosidade vai levar você?",
    topicIntro: "Escolha um ponto de partida. Cada tópico leva a uma coleção que vale a pena explorar.",
    features: [
      { title: "Selecionadas pelas comunidades", body: "Descubra ferramentas e recursos reunidos por quem os utiliza." },
      { title: "Leia no seu idioma", body: "Explore edições completas em inglês e em outros nove idiomas." },
      { title: "Mantenha o vínculo com a fonte", body: "As edições hospedadas apontam para revisões fixas dos originais; os demais repositórios abrem no GitHub." },
    ],
  },
  "ru-RU": {
    eyebrow: "Добро пожаловать на Awesome Site",
    title: "Меньше поисков. Больше открытий.",
    intro: "Найдите новый инструмент, идею или вдохновение в подборках открытого ПО от сообществ. Выберите тему, читайте на своём языке и переходите к первоисточнику.",
    explore: "Смотреть подборки",
    start: "Найти свою тему",
    collections: "Подборки на сайте",
    topics: "Темы для изучения",
    languages: "Языки чтения",
    topicTitle: "Куда приведёт ваше любопытство?",
    topicIntro: "Выберите отправную точку. Каждая тема ведёт к подборке, которую стоит изучить.",
    features: [
      { title: "Отобрано сообществами", body: "Откройте инструменты и ресурсы, собранные теми, кто ими пользуется." },
      { title: "Читайте на своём языке", body: "Полные версии подборок доступны на английском и ещё девяти языках." },
      { title: "Связь с первоисточником", body: "Версии на сайте ссылаются на закреплённые ревизии оригиналов; остальные репозитории открываются на GitHub." },
    ],
  },
};

/**
 * @param {string} locale
 * @returns {typeof welcomeCopy.root}
 */
export function getWelcomeCopy(locale) {
  if (!Object.hasOwn(welcomeCopy, locale)) {
    throw new Error(`Unsupported welcome locale "${locale}"`);
  }
  return welcomeCopy[locale];
}
